### ISSUE TITLE
copyWith parameters are not shown in code completion

### ISSUE THREAD

**Issue by vadrian89** [rrousselGit/freezed#346] opened 2021-01-16 12:31 UTC
Hello, not sure if this belongs in the bug secton or not but anyway, here I go.

**Describe the bug**
The way copyWith is implemented seems that it masks the parameters used from being discovered by code completion/lookup feature in both VS code and Android studio. 

**To Reproduce**
Any data class will do.
But for example let's use: 
```
abstract class ProdEntryModel with _$ProdEntryModel {
  @JsonSerializable(explicitToJson: true)
  factory ProdEntryModel({
    int id,
    int supplierId,
    String documentNumber,
    DateTime dateAdded,
    DateTime lastModified,
    DateTime documentDate,
    List<ProductModel> products,
  }) = _ProdEntryModel;

  factory ProdEntryModel.fromJson(Map<String, dynamic> data) =>
      _$ProdEntryModelFromJson(data);
}
```

**Expected behavior**
Named parameters should be discoverable by IDE for code completion/hinting/lookup (how do you want to name it. This makes it easier when I want to add an argument into copyWith and forgot how I named the parameter and/or to lookup if the field exists in that class.

In the above example, maybe I am thinking that I named the field "dateModified" instead of "lastModified". This can be with any other field, depending on the model and project, I might use a different naming.

Not just that, working with IDEs which offer code completion makes it weird  when I try to use copyWith,  it doesn't show what I am expecting and it disturbs the workflow.

Thank you for your work on the package though.

**Comment by smiLLe** [comment] 2021-01-16 14:53
This ist a problem in dart and for now you can fix this by writing
```dart
/// use .call()
final newProdEntryModel = prodEntryModel.copyWith.call( ... );
```

**Comment by rrousselGit** [comment] 2021-01-17 02:44
Duplicate of #137

**Closed by rrousselGit** 2021-01-17 02:44 UTC
Labels: bug, needs triage

**Comment by vadrian89** [comment] 2021-01-17 08:14
> This is a problem in dart and for now you can fix this by writing
> 
> ```dart
> /// use .call()
> final newProdEntryModel = prodEntryModel.copyWith.call( ... );
> ```

I see, thank you.
