### ISSUE TITLE
Allow using an enum annotated with @JsonValue in the FreezedUnionValue annotation

### ISSUE THREAD

**Issue by hacker1024** [rrousselGit/freezed#468] opened 2021-06-30 03:43 UTC
**Is your feature request related to a problem? Please describe.**
Using enums as FreezedUnionValue identifiers is safer and easier than using strings.

**Describe the solution you'd like**
`json_serializable` supports enum serialization and deserialization, through the use of the `@JsonValue('value')` annotation.

It'd be great to be able to do something like this:

Dart:

```dart
enum MyEnum {
  @JsonValue('value_1')
  value1,

  @JsonValue('value_2')
  value2,
}

@Freezed(unionKey: 'type')
class MyClass with _$MyClass {
  @FreezedUnionValue(MyEnum.value1);
  const factory MyClass.type1(/* ... */) = Type1MyClass;

  @FreezedUnionValue(MyEnum.value2);
  const factory MyClass.type2(/* ... */) = Type2MyClass;
}
```

JSON:

```json
{
  "type": "value_1",
  "...": "..."
}
```

**Describe alternatives you've considered**
Strings must be used instead.

**Additional context**

**Comment by hacker1024** [comment] 2021-06-30 03:45
I can try to implement this myself. Which API is preferred?

1. Let `FreezedUnionValue`'s default constructor take a dynamically typed argument, and throw an exception during code generation if it's not a String or enum
2. Add a `FreezedUnionValue.enum` constructor

**Comment by rrousselGit** [comment] 2021-06-30 08:41
What is the use-case for having an `enum` here? As Freezed should take care of this

**Comment by hacker1024** [comment] 2021-06-30 10:30
Consider an API like this:

`GET /permitted_upload_types`
Response:
```json
{
  "permittedTypes": ["track", "playlist", "station"]
}
```

`PUT /upload`
Request:
```json
{
  "type": "track",
  "...": "..."
}
```

It's common to have types included in API responses like this, to then be used as union types for requests (or vice-versa). Rather than using strings everywhere they show up, it's nicer to use enums.

**Comment by hacker1024** [comment] 2021-07-05 02:10
Another use case:

```json
{
  "ui_components": [
    {
      "type": "carousel",
      "items": ["..."],
      "slideDuration": 2000
    },
    {
      "type": "grid",
      "items": ["..."],
    }
  ],
  "form_factors": {
    "carousel": {"rows": 1, "columns": 5},
    "grid": {"rows": 2, "columns": 3}
  }
}
```

Here, I receive a list of UI items to display. I have a Freezed union for each type of UI component, and `type` is the union key. The `UIComponentType` enum is used for union values. I also use the `form_factors`, and convert them to a map of `UIComponentType`: `FormFactor`.

**Comment by rrousselGit** [comment] 2021-07-17 02:24
I don't think this is the correct solution.

Instead, we probably want #74, with the ability to deserialise ints/strings into Freezed objects and generate a static `values`:

```dart
@freezed
class Example with _$Example {
  factory Example.first() = _Example;
  factory Example.second(int a) = _Example2;

  factory Example.fromJson(String json) => _$ExampleFromJson(json);

  static const values = _$Example.values;
}
```

**Comment by rrousselGit** [comment] 2021-08-06 15:18
Closing this in favour of  #74 as I don't want to maintain two solutions to do the same thing in the long run.

**Closed by rrousselGit** 2021-08-06 15:18 UTC
Labels: enhancement, needs triage

**Comment by hacker1024** [comment] 2021-08-10 09:58
As far as I can tell, there's no plan to implement #74 though? I have a PR already.

**Comment by rrousselGit** [comment] 2021-08-10 10:29
#74 is going to be implemented at some point.

The problem is that while it's awesome that you made a PR, I am simply not convinced by the proposed solution.

Having to write the enum seems redundant to me. I don't see why this is preferable over taking the reverse approach, where Freezed would generate the enum instead.

**Comment by hacker1024** [comment] 2021-08-10 10:29
Also, I'm not too sure that #74 would actually let me do what I want to do. Here's a complete, real-world example, pulled directly from my project.

There's a list of `sections`. Each `Section` contains a `title` (which is a singular `Item`) and a list of subsection `Item`s.
Additionally, each type of `Item` has its own `FormFactor` data, which is given along with the `sections` in a `Map<ItemType, FormFactor>` structure.

Here's what my `Item` class would look like:

```dart
@Freezed(unionKey: 'type')
class Item with _$Item {
  @FreezedUnionValue(ItemType.banner)
  const factory Item.banner({
    @JsonKey(name: 'pandoraId') String? pandoraId,
    @JsonKey(name: 'analyticsToken') required String analyticsToken,
    @JsonKey(name: 'labels') required List<Label> labels,
    @JsonKey(name: 'image') Image? image,
  }) = BannerItem;

  @FreezedUnionValue(ItemType.belt)
  const factory Item.belt({
    @JsonKey(name: 'pandoraId') String? pandoraId,
    @JsonKey(name: 'analyticsToken') required String analyticsToken,
    @JsonKey(name: 'labels') List<Label>? labels,
    @JsonKey(name: 'image') required Image image,
    @JsonKey(name: 'action') Action? action,
    @JsonKey(name: 'longPressAction') Action? longPressAction,
    @JsonKey(name: 'voiceText') String? voiceText,
  }) = BeltItem;

  @FreezedUnionValue(ItemType.featured)
  const factory Item.featured({
    @JsonKey(name: 'pandoraId') String? pandoraId,
    @JsonKey(name: 'analyticsToken') required String analyticsToken,
    @JsonKey(name: 'labels') required List<Label> labels,
    @JsonKey(name: 'image') required Image image,
    @JsonKey(name: 'action') Action? action,
    @JsonKey(name: 'longPressAction') Action? longPressAction,
    @JsonKey(name: 'badges') List<Badge>? badges,
  }) = FeaturedItem;

  // etc.

  factory Item.fromJson(Map<String, dynamic> json) =>
      _$ItemFromJson(json);
}
```

And my class containing the `sections` and `FormFactor` data:

```dart
@freezed
class DirectoryResponse with _$DirectoryResponse {
  const factory DirectoryResponse({
    @JsonKey(name: 'sections') required List<Section> sections,
    @JsonKey(name: 'formFactorsByType')
        required Map<ItemType, FormFactors> formFactorsByType,
  }) = _DirectoryResponse;

  factory DirectoryResponse.fromJson(Map<String, dynamic> json) =>
      _$DirectoryResponseFromJson(json);
}
```

When serializing to JSON, the `ItemType`'s annotated `JsonValue` must be used as both a `Item` union value and as a key in the form factor map.

Here's the JSON (sorry for the size):

```json
{
  "sections": [
    {
      "id": "BS:1:41",
      "title": {
        "type": "banner",
        "image": {
          "fullUrl": "https://content-images.p-cdn.com/images/public/int/sb/browse_images/Logo/Pandora_Logo_3x.png"
        },
        "labels": [
          {
            "text": "Good morning! This is your Saturday",
            "style": "banner",
            "alignment": "center",
            "maxLines": 2
          }
        ],
        "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"0\",\"secType\":\"header\",\"inum\":\"0\",\"itype\":\"banner\",\"secId\":\"BS:1:41\"}"
      }
    },
    {
      "id": "BS:1:53:21547673299880356",
      "subsections": [
        {
          "subsectionType": "horizontalScroll",
          "items": [
            {
              "type": "featured",
              "action": {
                "type": "backstage",
                "pandoraId": "GE:10306"
              },
              "image": {
                "scalableUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2F18%2Fc2%2F2c%2Faa%2Fea7a44adb82f36b6fb5e816c%2F%3Boverlay($0)&c=90&f=jpeg",
                "sizedUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2F18%2Fc2%2F2c%2Faa%2Fea7a44adb82f36b6fb5e816c%2F%3Boverlay($0)&c=90&f=jpeg&w=$W$&h=$H$",
                "border": true,
                "dominantColor": "",
                "discreteSizes": [
                  "90x90",
                  "130x130",
                  "500x500",
                  "640x640",
                  "1080x1080"
                ]
              },
              "labels": [
                {
                  "text": "Rockin' in the Free World",
                  "style": "title",
                  "alignment": "left"
                },
                {
                  "text": "823 listeners",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "Rockin' in the Free World is your eclectic rock soundtrack to celebrate the awesomeness that is America.",
                  "style": "description",
                  "alignment": "left",
                  "maxLines": 2
                }
              ],
              "badges": [
                {
                  "type": "collected"
                }
              ],
              "pandoraId": "GE:10306",
              "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"1\",\"secType\":\"horizontalScroll\",\"id\":\"GE:10306\",\"inum\":\"0\",\"itype\":\"featured\",\"secId\":\"BS:1:53:21547673299880356\"}",
              "alignment": "left"
            },
            {
              "type": "featured",
              "action": {
                "type": "backstage",
                "pandoraId": "GE:1033"
              },
              "image": {
                "scalableUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2Fe0%2Fc6%2F67%2Fae%2F460a497cb1451f4d5433a93d%2F%3Boverlay($0)&c=90&f=jpeg",
                "sizedUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2Fe0%2Fc6%2F67%2Fae%2F460a497cb1451f4d5433a93d%2F%3Boverlay($0)&c=90&f=jpeg&w=$W$&h=$H$",
                "border": true,
                "dominantColor": "",
                "discreteSizes": [
                  "90x90",
                  "130x130",
                  "500x500",
                  "640x640",
                  "1080x1080"
                ]
              },
              "labels": [
                {
                  "text": "Patriotic Country",
                  "style": "title",
                  "alignment": "left"
                },
                {
                  "text": "1.3M listeners",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "Patriotic Country plays your favorite country artists' homages to our great nation. Just what you need for that 4th of July barbecue and Memorial Day beach day.",
                  "style": "description",
                  "alignment": "left",
                  "maxLines": 2
                }
              ],
              "badges": [
                {
                  "type": "collected"
                }
              ],
              "pandoraId": "GE:1033",
              "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"1\",\"secType\":\"horizontalScroll\",\"id\":\"GE:1033\",\"inum\":\"1\",\"itype\":\"featured\",\"secId\":\"BS:1:53:21547673299880356\"}",
              "alignment": "left"
            },
            {
              "type": "featured",
              "action": {
                "type": "backstage",
                "pandoraId": "GE:1038"
              },
              "image": {
                "scalableUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2Fcf%2F5d%2F97%2Fc3%2Fddbb4ca1a979fe32190b1a66%2F%3Boverlay($0)&c=90&f=jpeg",
                "sizedUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2Fcf%2F5d%2F97%2Fc3%2Fddbb4ca1a979fe32190b1a66%2F%3Boverlay($0)&c=90&f=jpeg&w=$W$&h=$H$",
                "border": true,
                "dominantColor": "",
                "discreteSizes": [
                  "90x90",
                  "130x130",
                  "500x500",
                  "640x640",
                  "1080x1080"
                ]
              },
              "labels": [
                {
                  "text": "Classical Fireworks",
                  "style": "title",
                  "alignment": "left"
                },
                {
                  "text": "211K listeners",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "Classical Fireworks is the nostalgic sound of Independence Day celebrations past and present. Listen to this station and imagine laying on a blanket underneath the stars as lights blossom in the night sky alongside these iconic sounds.",
                  "style": "description",
                  "alignment": "left",
                  "maxLines": 2
                }
              ],
              "badges": [
                {
                  "type": "collected"
                }
              ],
              "pandoraId": "GE:1038",
              "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"1\",\"secType\":\"horizontalScroll\",\"id\":\"GE:1038\",\"inum\":\"2\",\"itype\":\"featured\",\"secId\":\"BS:1:53:21547673299880356\"}",
              "alignment": "left"
            },
            {
              "type": "featured",
              "action": {
                "type": "backstage",
                "pandoraId": "GE:10308"
              },
              "image": {
                "scalableUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2F09%2F16%2F42%2F1a%2F8a694b7993cf52f21cddb17d%2F%3Boverlay($0)&c=90&f=jpeg",
                "sizedUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2F09%2F16%2F42%2F1a%2F8a694b7993cf52f21cddb17d%2F%3Boverlay($0)&c=90&f=jpeg&w=$W$&h=$H$",
                "border": true,
                "dominantColor": "",
                "discreteSizes": [
                  "90x90",
                  "130x130",
                  "500x500",
                  "640x640",
                  "1080x1080"
                ]
              },
              "labels": [
                {
                  "text": "Red White & BLUES BBQ",
                  "style": "title",
                  "alignment": "left"
                },
                {
                  "text": "401 listeners",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "The Blues are American-born and raised, making this the perfect soundtrack to a patriotic backyard get together.",
                  "style": "description",
                  "alignment": "left",
                  "maxLines": 2
                }
              ],
              "badges": [
                {
                  "type": "collected"
                }
              ],
              "pandoraId": "GE:10308",
              "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"1\",\"secType\":\"horizontalScroll\",\"id\":\"GE:10308\",\"inum\":\"3\",\"itype\":\"featured\",\"secId\":\"BS:1:53:21547673299880356\"}",
              "alignment": "left"
            },
            {
              "type": "featured",
              "action": {
                "type": "backstage",
                "pandoraId": "GE:10310"
              },
              "image": {
                "scalableUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2F36%2F0c%2F36%2F92%2F12bc4d05b2150b47bb203669%2F%3Boverlay($0)&c=90&f=jpeg",
                "sizedUrl": "https://dyn-images.p-cdn.com/?l=images/thor_assets/rings%3Bimages%2F36%2F0c%2F36%2F92%2F12bc4d05b2150b47bb203669%2F%3Boverlay($0)&c=90&f=jpeg&w=$W$&h=$H$",
                "border": true,
                "dominantColor": "",
                "discreteSizes": [
                  "90x90",
                  "130x130",
                  "500x500",
                  "640x640",
                  "1080x1080"
                ]
              },
              "labels": [
                {
                  "text": "Hipster 4th of July BBQ",
                  "style": "title",
                  "alignment": "left"
                },
                {
                  "text": "366 listeners",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "",
                  "style": "detail",
                  "alignment": "left"
                },
                {
                  "text": "Hipster 4th of July BBQ is your soundtrack to the ultimate patriotic BBQ. So lie back on the lawn with a beer and enjoy a mix of upbeat summery indie music favorites.",
                  "style": "description",
                  "alignment": "left",
                  "maxLines": 2
                }
              ],
              "badges": [
                {
                  "type": "collected"
                }
              ],
              "pandoraId": "GE:10310",
              "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"1\",\"secType\":\"horizontalScroll\",\"id\":\"GE:10310\",\"inum\":\"4\",\"itype\":\"featured\",\"secId\":\"BS:1:53:21547673299880356\"}",
              "alignment": "left"
            }
          ],
          "sectionId": "BS:1:53:21547673299880356",
          "scrollType": "snap",
          "formFactors": {
            "portrait": {
              "numRows": 1,
              "numCols": 1
            },
            "landscape": {
              "numRows": 1,
              "numCols": 2
            }
          }
        }
      ],
      "title": {
        "type": "header",
        "labels": [
          {
            "text": "Patriotic Party Time",
            "style": "header"
          },
          {
            "text": "Spin these summer-ready, celebratory favorites",
            "style": "detail"
          }
        ],
        "analyticsToken": "{\"generation\":\"1625314732298\",\"timezone\":\"AEST\",\"snum\":\"1\",\"secType\":\"header\",\"inum\":\"0\",\"itype\":\"header\",\"secId\":\"BS:1:53:21547673299880356\"}"
      }
    },
  ],
  "formFactorsByType": {
    "featured": {
      "portrait": {
        "numCols": 2,
        "span": 1
      },
      "landscape": {
        "numCols": 4,
        "span": 1
      }
    },
    "grid": {
      "portrait": {
        "numCols": 2,
        "span": 1
      },
      "landscape": {
        "numCols": 4,
        "span": 1
      }
    },
    "banner": {
      "portrait": {
        "numCols": 2,
        "span": 2
      },
      "landscape": {
        "numCols": 4,
        "span": 4
      }
    },
    "small_row": {
      "portrait": {
        "numCols": 2,
        "span": 2
      },
      "landscape": {
        "numCols": 4,
        "span": 4
      }
    },
    "large_row": {
      "portrait": {
        "numCols": 2,
        "span": 2
      },
      "landscape": {
        "numCols": 4,
        "span": 4
      }
    },
    "empty": {
      "portrait": {
        "numCols": 2
      },
      "landscape": {
        "numCols": 4
      }
    },
    "card": {
      "portrait": {
        "numCols": 2
      },
      "landscape": {
        "numCols": 4
      }
    },
    "footer": {
      "portrait": {
        "numCols": 2,
        "span": 2
      },
      "landscape": {
        "numCols": 4,
        "span": 4
      }
    },
    "header": {
      "portrait": {
        "numCols": 2,
        "span": 2
      },
      "landscape": {
        "numCols": 4,
        "span": 4
      }
    },
    "hero": {
      "portrait": {
        "numCols": 2,
        "span": 2
      },
      "landscape": {
        "numCols": 4,
        "span": 4
      }
    },
    "belt": {
      "portrait": {
        "numCols": 2,
        "span": 1
      },
      "landscape": {
        "numCols": 4,
        "span": 1
      }
    },
    "picture": {
      "portrait": {
        "numCols": 2
      },
      "landscape": {
        "numCols": 4
      }
    },
    "tile": {
      "portrait": {
        "numCols": 2,
        "span": 1
      },
      "landscape": {
        "numCols": 4,
        "span": 1
      }
    },
    "button": {
      "portrait": {
        "numCols": 2
      },
      "landscape": {
        "numCols": 4
      }
    },
    "split": {
      "portrait": {
        "numCols": 2,
        "span": 1
      },
      "landscape": {
        "numCols": 4,
        "span": 1
      }
    }
  }
}
```

**Comment by hackwaly** [comment] 2023-04-01 06:28
Can I use `int` as union value type? I can see the advantage of @hacker1024 's proposal. @hacker1024, Where can I find your fork?
