### ISSUE TITLE
Incorrect handling of the generated union class as a field in another Freezed data class

### ISSUE THREAD

**Issue by proninyaroslav** [rrousselGit/freezed#253] opened 2020-08-24 15:01 UTC
Hi. I recently ran into the following problem. Let's say we have two Freezed-classes - union and data class:

```Dart
// my_union.dart

@freezed
abstract class MyUnion with _$MyUnion {
  const factory MyUnion({@required int a, int b}) = MyUnionValues;
  const factory MyUnion.one() = MyUnionOne;
  const factory MyUnion.two() = MyUnionTwo;
}
```

```Dart
// my_data.dart

@freezed
abstract class MyData with _$MyData {
  const factory MyData({
    @required MyUnionValues unionValues, 
    int c,
  }) = _MyData;
}
```
but `unionValues` in `MyData` generated code was `dynamic`, like this:
```Dart
// my_data.freezed.dart

...

mixin _$MyData {
  dynamic get unionValues;
  int get c;
}

...
```
I tried to run `build_runner` without deleting the file, but it didn't work, it was still `dynamic`.
I will fix this by deleting the generated file (`my_data.freezed.dart`) and running `build_runner` again. 
As far as I understood, there is a conflict when generating the code. During `MyData` generation, `MyUnionValues` didn't exist yet, so Freezed marked the `unionValues` getter as `dynamic`. After I deleted `my_data.freezed.dart` and generated it again, `MyUnionValues` class already existed and Freezed generated the correct `MyData` code.

**Comment by proninyaroslav** [comment] 2020-08-25 09:54
Faced it again today.

**Comment by proninyaroslav** [comment] 2020-09-08 18:22
@rrousselGit 
Can you comment on this situation?

**Comment by rrousselGit** [comment] 2020-09-08 18:40
What version of Freezed are you using? I would expect this to work in theory

**Comment by proninyaroslav** [comment] 2020-09-08 18:41
@rrousselGit 
0.11.6

**Comment by rrousselGit** [comment] 2020-09-08 20:41
Hum I cannot reproduce

On my end, `MyData` correctly generates from the get-go.

**Comment by proninyaroslav** [comment] 2020-09-09 07:36
@rrousselGit 
Yes, it cannot be reproduced reliably. It usually appears when I build with the `--delete-conflicting-outputs` flag, or when I make a lot of changes to the codebase.

**Comment by rrousselGit** [comment] 2021-08-06 16:21
I will close this since this likely got fixed in previous versions. Fill free to open a new issue if you still have the problem

**Closed by rrousselGit** 2021-08-06 16:21 UTC
Labels: bug
