### ISSUE TITLE
Support for .merge() method

### ISSUE THREAD

**Issue by strigePC** [rrousselGit/freezed#510] opened 2021-09-01 17:28 UTC
Flutter have a neat method on some classes that allows to merge two object of the same type (e.g. [TextTheme.merge](https://api.flutter.dev/flutter/material/TextTheme/merge.html)). In its implementation it uses a copyWith() method to fill out the fields.

It would be nice if the freezed package would have similar feature as it already supports copyWith() method. I think it would be a great addition to the package

**Comment by rrousselGit** [comment] 2021-09-01 19:35
I'm not really convinced by a generated "merge" utility.  I doubt that the generated code would be reliable, as the merge logic isn't necessarily obvious (like "how to handle default values")

What is the use-case exactly? From experience, it seems to be used primarily as a "copyWith".

**Comment by dossiman** [comment] 2021-09-17 08:15
I was also looking for such feature but I don't think we can use freezed's copyWith to simulate the behavior of flutter's merge methods.
If I understand correctly, by design freezed is treating null values as real values to be copied over. While TextStyle and *Theme merge() methods are basically just passing all the fields to a copyWith() that ignores null values. This is how the "merging" is done, the created object will "inherit" a field from the object that has a non null value (or from the object passed as parameter if they both have a non value for that field). For instance:
```
  final parentTheme = IconThemeData(color: Color(0xffffffff), size: 24);
  final myTheme = IconThemeData(color: Color(0xff000000), opacity: 1);
  final mergedTheme = parentTheme.merge(myTheme);
  // IconThemeData(color: Color(0xff000000), opacity: 1.0, size: 24.0)
```
mergedTheme will get opacity from myTheme but size from parentTheme (and since color is defined in both, by design it will use the value of myTheme).
But with freezed's copyWith style, the null values of myTheme will override the values of parentTheme, so it ends up producing a clone of myTheme.

It would be nice to be able to make freezed data types for custom Theme and Style, but for that we would also need the option to choose the way null values are handled by the copyWith, I couldn't find a way to override this behavior.

**Comment by a-eniou-pvotal** [comment] 2022-01-05 15:58
I saw your comment for this issue
https://github.com/rrousselGit/freezed/issues/94
So here is the usage case:
I scrap website pages [Home, About]
but home maybe has a phone number or About could have it so I would need to merge all scraped objects together where fields are not empty or if int ==0,
If I used copyWith it will not save any code
Merge:
```
  Company merge({
    required IndeedCompany other,
  }) {
    return Company(
      companyId: companyId.isNotEmpty ? companyId : other.companyId,
      companyName: companyName.isNotEmpty ? companyName : other.companyName,
}
```
CopyWith
```
  Company merge({
    required IndeedCompany other,
  }) {
    return copyWith(
      companyId: companyId.isNotEmpty ? companyId : other.companyId,
      companyName: companyName.isNotEmpty ? companyName : other.companyName,
}
```

So almost identical and I didn’t save any code

**Comment by victor-tinoco** [comment] 2022-03-10 19:53
Any update about it?

**Comment by rrousselGit** [comment] 2022-04-16 08:38
I don't plan on working on this as this is fairly unreliable, so I'll close this.

**Closed by rrousselGit** 2022-04-16 08:38 UTC
Labels: enhancement
