### ISSUE TITLE
VSCode Intellisense suggestions do not work with copyWith() method

### ISSUE THREAD

**Issue by popay34** [rrousselGit/freezed#459] opened 2021-06-07 08:44 UTC
Hello! I have been observing this problem for a very long time. Why there are no Intellisense suggestions when i use copyWith() method?
![1](https://user-images.githubusercontent.com/60180239/120986083-e5350600-c784-11eb-97bf-d1a532db2dd7.png)
![Скрин 2](https://user-images.githubusercontent.com/60180239/120986800-a3588f80-c785-11eb-8a90-f69b8c3d1351.png)

**Comment by rrousselGit** [comment] 2021-06-07 19:03
Duplicate of https://github.com/rrousselGit/freezed/issues/137

**Closed by rrousselGit** 2021-06-07 19:03 UTC
Labels: bug, needs triage
