### ISSUE TITLE
Do not resolved `typedef`s for records

### ISSUE THREAD

**Issue by tp** [rrousselGit/freezed#1001] opened 2023-10-24 08:33 UTC
When using `typedef` to define records (e.g. `typedef User = ({ int id, String name })`) the generated `freezed`-class constructor inline the record description (`({ int id, String name })`) instead of the "type name" (`User`).

**Describe the solution you'd like**

I would like to see `freezed` use the same type name in the generated constructor as I used in the `factory` one (i.e. not "following" the `typedef`).

The benefit would be that I can change the `typedef User = …` without having to regenerate all the `freezed` classes (which then just inline the new definition).

<details><summary>**Additional context**</summary>
<p>

Something like the following class would be generated:

```dart
abstract class UserStateLoaded implements UserState {
  factory UserStateLoaded(
      final ({ int id, String name }) user) = _$UserStateLoaded;
}
```

where I think

```dart
abstract class UserStateLoaded implements UserState {
  factory UserStateLoaded(
      final User user) = _$UserStateLoaded;
}
```

would be preferrable.

</p>
</details> 

This might relate to https://github.com/rrousselGit/freezed/issues/753

**Comment by rrousselGit** [comment] 2023-10-24 08:34
Closing as duplicate of #753

**Closed by rrousselGit** 2023-10-24 08:34 UTC
Labels: enhancement, needs triage
