### ISSUE TITLE
Properties in copyWith don't show in suggestion

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/freezed#199] opened 2020-06-13 13:59 UTC
<img width="690" alt="Screen Shot 2020-06-13 at 8 57 13 PM" src="https://user-images.githubusercontent.com/52562340/84570613-c641a500-adb8-11ea-9255-6c3f5055c34b.png">

**Comment by rrousselGit** [comment] 2020-06-13 14:08
Duplicate of #137

**Closed by rrousselGit** 2020-06-13 14:08 UTC
