### ISSUE TITLE
Lack of information about web support

### ISSUE THREAD

**Issue by erluxman** [rrousselGit/freezed#800] opened 2022-11-15 04:35 UTC
Based on the nature of this project as it's a code generator, normally it would not be platform dependent. But still, I am concerned about why Web support is not mentioned in the pub.dev?

Or it does it not support web for some reason?

**Comment by SunlightBro** [comment] 2022-11-15 08:22
Duplicate of [#799](https://github.com/rrousselGit/freezed/issues/799#issuecomment-1313950341). Can be closed.

**Comment by rrousselGit** [comment] 2022-11-15 09:25
You already made an issue about it, and it was already answered

**Closed by rrousselGit** 2022-11-15 09:25 UTC
Labels: bug, needs triage
