### ISSUE TITLE
[Question] dart-json-mapper

### ISSUE THREAD

**Issue by bounty1342** [rrousselGit/freezed#96] opened 2020-03-08 22:24 UTC
Hi there,

We use [dart-json-mapper](https://github.com/k-paxian/dart-json-mapper/issues/45) as our Json serializer.
Since Freezed already support decorator, I'm wondering how difficult it will be to add it next to json_serializer ?

Regards

Ps: [Issue#83](https://github.com/rrousselGit/freezed/issues/83) might also solve it, but in a less optimal manner.

**Comment by rrousselGit** [comment] 2020-03-08 23:10
Hi

I do not really understand. What's the purpose, and what do you need?

**Comment by bounty1342** [comment] 2020-03-09 00:07
I'll try to give more context.

```
While Freezed will not generate your typical fromJson/toJson by itself, it knowns what **json_serializable** is.
Making a class compatible with json_serializable is very straightforward.
```
I would like to be able to do the same with https://github.com/k-paxian/dart-json-mapper witch we already deploy on our project.

I tried to mix both Freezed with Dart_json_mapper below :
![Screen Shot 2020-03-09 at 12 59 03 AM](https://user-images.githubusercontent.com/6307253/76173630-38df2b00-61a1-11ea-9a2b-55f0f741e08a.png)

Out of the build, there is several error if the generated file :

> "The name 'JsonSerializable' is defined in the libraries package:dart_json_mapper/src/model/annotations.dart' and 'package:json_annotation/src/json_serializable.dart'."

Hope this make sense.

**Comment by rrousselGit** [comment] 2020-03-09 00:14
But what does that bring you over using json_serializable?

**Comment by bounty1342** [comment] 2020-03-09 00:29
Enum, inheritance, and custom types converter are features that stand out for me.

**Comment by rrousselGit** [comment] 2020-03-09 00:34
Could you extend on this with concrete example and how that would related to freeze?

**Comment by bounty1342** [comment] 2020-03-09 00:44
The two package at this time don't mix correctly (Concrete exemple on the screenshot). 
My point was see if it was possible to resolve this.

I personally think we should have the choice to use the serializer we want.

**Comment by rrousselGit** [comment] 2020-03-09 00:48
Freezed does not support dart-json-mapper, so it not working is expected.

The equation is: why would be the benefits of having Freezed support it?

**Comment by bounty1342** [comment] 2020-03-12 22:42
Not sure how to respond to be honest. I could state that is a good thing to be agnostic, so it broaden the possibility and as stated before let the users choose what they want. 

On a personal note, I wanted to add Freezed to my project but already have my serialization handle with dart-json-mapper. Like your projet, it provide a convenient way for us to handle a purpose (Certainly the Java-Jackson parity that got our attention at the beginning)

Finally, I don't expect of you to support dart-json-mapper, but it will be great if both package were not incompatible.

If you still think this is not needed/useful, you can close the issue with no harm done. 🤙

**Comment by rrousselGit** [comment] 2020-03-12 22:47
I'm not against it. But the work to be done would be quite important. As it stands, I don't see why I would work on that when I can do something else more useful.

The best I can do is remove the hard dependency on `json_annotation` and require people to import it themselves (which is not a bad idea anyway). 

This would solve the conflict (although you can fix it yourself through `import 'freezed_annotation/...' hide JsonSerialization'

**Comment by RaviKavaiya** [comment] 2020-05-04 11:21
@rrousselGit I also want to combine these both libraries.
I tried to put the `@jsonSerializable` on the constructor created by freezed. It passes the decorator to generated constructor.

But, the problem is, the generated constructor is private (starts with `_`) and the reflectable file created by dart-json-mapper can't simply access that.

**Comment by rrousselGit** [comment] 2020-06-05 00:57
Closing as I have no plan to work on this

**Closed by rrousselGit** 2020-06-05 00:57 UTC
Labels: question
