### ISSUE TITLE
GlobalState for any factories

### ISSUE THREAD

**Issue by II11II** [rrousselGit/freezed#378] opened 2021-03-04 17:01 UTC
I'm always frustrated when I should define the same state in each factory parameter like this.
```
@freezed
abstract class LoginState with _$LoginState {


  const factory LoginState.initial({String token,String login}) = _Initial;
  const factory LoginState.loading({String token,String login}) = _Loading;
  const factory LoginState.success({String token,String login}) = _Initial;
  const factory LoginState.failure({String token,String login,String? e}) = _Failure;

 
}
```

**Describe the solution you'd like**
```

@freezed
abstract class LoginState with _$LoginState {
  @GlobalState String token;
@GlobalState String login;

  const factory LoginState.initial() = _Initial;
  const factory LoginState.loading() = _Loading;
  const factory LoginState.success() = _Initial;
  const factory LoginState.failure({String? e}) = _Failure;

 
}


```

**Comment by rrousselGit** [comment] 2021-03-04 17:19
How do you expect `token` and `login` to be initialized?

**Comment by II11II** [comment] 2021-03-04 17:24
By any factory (f.e. by factory LoginState. success())
I would not like to lose token if I change the state

**Comment by rrousselGit** [comment] 2021-03-04 17:25
Could you expand with a complete example, possible one that compiles?

**Comment by II11II** [comment] 2021-03-04 17:32
```
class LoginState {
  late String token;
  late String login;
}

class _$LoginInital extends LoginState {}

class _$LoginError extends LoginState {
  late String e;
}

class _$LoginSuccess extends LoginState {}

main(List<String> args) {
  LoginState state = LoginState();
  state.login;
  LoginState state2 = _$LoginInital();
  state2.login;
  LoginState state3 = _$LoginError();
  state3.login;

}


```

**Comment by rrousselGit** [comment] 2021-03-04 17:35
Freezed does not allow mutable properties by design

**Comment by II11II** [comment] 2021-03-04 17:47
What would recommend me to be accessible these state ```login``` and  ```token```  from any 'factory' ?

**Comment by II11II** [comment] 2021-03-04 17:55
> Freezed does not allow mutable properties by design
Now it is immutable 
```

@immutable
class LoginState {
  final String? token;
  final String? login;

  LoginState({this.token, this.login});
}

class _$LoginInital extends LoginState {
  _$LoginInital({String? login, String? token})
      : super(login: login, token: token);
}

class _$LoginError extends LoginState {
  final String? e;

  _$LoginError({String? login, String? token, this.e})
      : super(login: login, token: token);
}

class _$LoginSuccess extends LoginState {
  _$LoginSuccess({String? login, String? token})
      : super(login: login, token: token);
}


```

**Comment by II11II** [comment] 2021-03-04 17:56
> > Freezed does not allow mutable properties by design
> > Now it is immutable
> 
> ```
> 
> @immutable
> class LoginState {
>   final String? token;
>   final String? login;
> 
>   LoginState({this.token, this.login});
> }
> 
> class _$LoginInital extends LoginState {
>   _$LoginInital({String? login, String? token})
>       : super(login: login, token: token);
> }
> 
> class _$LoginError extends LoginState {
>   final String? e;
> 
>   _$LoginError({String? login, String? token, this.e})
>       : super(login: login, token: token);
> }
> 
> class _$LoginSuccess extends LoginState {
>   _$LoginSuccess({String? login, String? token})
>       : super(login: login, token: token);
> }
> ```

Here will be needed copyWith method

**Comment by rrousselGit** [comment] 2021-03-04 18:04
How is this different from what we currently have? If the property is final, we still need to define the parameters on all cases of the union

**Comment by II11II** [comment] 2021-03-04 18:28
> How is this different from what we currently have? If the property is final, we still need to define the parameters on all cases of the union

But it loses data token and login if don't 

> > > Freezed does not allow mutable properties by design
> > > Now it is immutable
> > 
> > 
> > ```
> > 
> > @immutable
> > class LoginState {
> >   final String? token;
> >   final String? login;
> > 
> >   LoginState({this.token, this.login});
> > }
> > 
> > class _$LoginInital extends LoginState {
> >   _$LoginInital({String? login, String? token})
> >       : super(login: login, token: token);
> > }
> > 
> > class _$LoginError extends LoginState {
> >   final String? e;
> > 
> >   _$LoginError({String? login, String? token, this.e})
> >       : super(login: login, token: token);
> > }
> > 
> > class _$LoginSuccess extends LoginState {
> >   _$LoginSuccess({String? login, String? token})
> >       : super(login: login, token: token);
> > }
> > ```
> 
> Here will be needed copyWith method

```
@immutable
abstract class LoginState {
  final String? token;
  final String? login;

  LoginState({this.token, this.login});
}

class _$LoginInital extends LoginState {
  _$LoginInital({String? login, String? token})
      : super(login: login, token: token);
  _$LoginInital copyWith({
    String? e,
    String? login,
    String? token,
  }) {
    return _$LoginInital(
      login: login ?? super.login,
      token: token ?? this.token,
    );
  }
}

class _$LoginError extends LoginState {
  final String? e;

  _$LoginError({String? login, String? token, this.e})
      : super(login: login, token: token);

  _$LoginError copyWith({
    String? e,
    String? login,
    String? token,
  }) {
    return _$LoginError(
      e: e ?? this.e,
      login: login ?? super.login,
      token: token ?? this.token,
    );
  }
}

class _$LoginSuccess extends LoginState {
  _$LoginSuccess({String? login, String? token})
      : super(login: login, token: token);
  _$LoginSuccess copyWith({
    String? e,
    String? login,
    String? token,
  }) {
    return _$LoginSuccess(
      login: login ?? super.login,
      token: token ?? this.token,
    );
  }
}



```

**Comment by II11II** [comment] 2021-03-04 18:30
> How is this different from what we currently have? If the property is final, we still need to define the parameters on all cases of the union

But if I dont pass the parameter it loses data login and token in freezer way 
```

  const factory LoginState.initial({String token,String login}) = _Initial;
  const factory LoginState.loading({String token,String login}) = _Loading;
  const factory LoginState.success({String token,String login}) = _Initial;
  const factory LoginState.failure({String token,String login,String? e}) = _Failure;

```

**Comment by II11II** [comment] 2021-03-04 18:39
Maybe, I am doing this in wrong way, Could you navigate how to correctly copyState to new one

**Comment by rrousselGit** [comment] 2021-03-09 11:37
it is your responsibility to keep a reference on `token` and `logen` across state-change. Freezed cannot do that for you

In the same fashion, there is no way for Freezed to allow sharing constructor parameter between constructor. So there's nothing we can do here, so I'll close this

**Closed by rrousselGit** 2021-03-09 11:37 UTC
Labels: enhancement, needs triage
