### ISSUE TITLE
Type set to dynamic when using a specific type of an union type with a generic parameter

### ISSUE THREAD

**Issue by fischerscode** [rrousselGit/freezed#841] opened 2023-01-16 02:18 UTC
**Describe the bug**
When using a specific type of an union type with a generic parameter in a factory, freezed sets the type to `dynamic`.

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';

@freezed
class Foo<T> with _$Foo {
  const factory Foo.one(T a) = FooOne;
  const factory Foo.two(T a, T b) = FooTwo;
}

@freezed
class Bar<T> with _$Bar {
  const factory Bar(Foo<T> a, FooTwo<T> b) = _Bar; // same for _Bar<T>;
}
```

**Expected behavior**
`Bar<T>(..., ...).b` should have the type `FooTwo<T>`

**Comment by rrousselGit** [comment] 2023-01-16 10:06
You cannot rely on `FooTwo` as input of another Freezed class.

This is a known limitation and won't be fixed until static metaprogramming.

Either separate your two classes in different classes or don't rely on FooTwo

**Closed as completed by rrousselGit** 2023-01-16 10:06 UTC
Labels: bug, needs triage

**Comment by fischerscode** [comment] 2023-01-16 14:17
Ok, thanks for the clarification.

I thought it might be a bug since this example works.
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';

@freezed
class Foo with _$Foo {
  const factory Foo.one(int a) = FooOne;
  const factory Foo.two(int a, T b) = FooTwo;
}

@freezed
class Bar with _$Bar {
  const factory Bar(Foo a, FooTwo b) = _Bar; 
}
```

## workaround
A workaround, in case anyone else runs into this limitation:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';

@freezed
class Foo<T> with _$Foo<T> {
  const factory Foo.one(T a) = FooOne;
  @Implements<FooTwo<T>>()
  const factory Foo.two(T a, T b) = _FooTwo;
}

abstract class FooTwo<T> implements Foo<T> {
  const factory FooTwo(T a, T b) = _FooTwo;
  @override
  T get a;
  T get b;

  @override
  // ignore: library_private_types_in_public_api
  _$$_FooTwoCopyWith<T, _$_FooTwo<T>> get copyWith;
}

@freezed
class Bar<T> with _$Bar<T> {
  const factory Bar(Foo<T> a, FooTwo<T> b) = _Bar;
}
```

**Comment by rrousselGit** [comment] 2023-01-16 15:04
> I thought it might be a bug since this example works.

Depends actually.
It's not supposed to work, but there's a random chance that it will.
It's unreliable.


The problem is that since the class doesn't exist when `Freezed` will execute, the class parsing fails (and fallbacks to dynamic).
But sometimes the class might exist from a previous run of the code-generator and therefore the parsing passes.
