### ISSUE TITLE
Nullable fields being marked as non nullable

### ISSUE THREAD

**Issue by abahnj** [rrousselGit/freezed#380] opened 2021-03-05 15:45 UTC
**Describe the bug**
After my upgrade to version 0.14 previously working models give non nullable errors

**To Reproduce**

@freezed
 class ServerError implements _$ServerError {
  const factory ServerError({
    int statusCode,
    String error,
    String message,
  }) = _ServerError;

  const ServerError._();

  factory ServerError.fromRawJson(String str) =>
      ServerError.fromJson(json.decode(str));

  String toRawJson() => json.encode(toJson());

  factory ServerError.fromJson(Map<String, dynamic> json) =>
      _$ServerErrorFromJson(json);
}

**Expected behavior**
Models to be built as the values are nullable since I haven't opted in to sound null safety

**Comment by rrousselGit** [comment] 2021-03-05 20:09
Could you expand on what your problem is? I don't quite understand

**Comment by TimWhiting** [comment] 2021-03-06 05:32
I believe the issue is that version `^0.14.0` only generates code for null-safe libraries. 

@abahnj 
If you are not opted in you should be using version `^0.12.7`, which you should still be able to use in your code even with the latest Flutter / Dart SDKs.

**Comment by rrousselGit** [comment] 2021-03-06 07:58
Oh, let me document that quickly

**Comment by davidmartos96** [comment] 2021-03-06 08:01
@rrousselGit I got this error recently. Another point to make if you are going to update the docs is regarding compatibility with other packages. 
For instance, device_preview null safe uses freezed null safe, so if you want to be in compatibility mode, the freezed_anotation packages has to be overrided in the pubspec to 0.12.0, otherwise it will yell with missmatch errors

**Comment by rrousselGit** [comment] 2021-03-06 08:05
I've added a note in the readme about 0.14.0 vs 0.12.7 and using dependency_overrides for annotation conflict.

**Comment by TimWhiting** [comment] 2021-03-06 18:56
About this:
It would be nice to still have the nullable annotation in the null-safe version at least during the migration time period, or just a specific dev release with the annotation so that people can upgrade their dependency to the null-safe version prior to migration. Otherwise `dart migrate` complains about not all dependencies being migrated, but you can't update to the null-safe version because it complains about the @nullable annotation. So there doesn't seem to be a clear path for migration if you have freezed classes. If you could clarify the path for migration that would be helpful.

The easiest way for me to migrate was to:
1. Ignore the warning from dart migrate, and migrate with the non-nullsafe version of freezed (but null-safe versions of the other packages). This migrates the generated code as well unfortunately (I just ignored the file while migrating, since I knew I was going to be regenerating it)
2. Upgrade the freezed version to the null safe version
3. Remove the @nullable annotation and make sure the fields now have ? on them
4. Run the null-safe freezed generator.

Thinking back on it maybe a better solution would be:
1. Update all dependencies
2. Delete the generated files
3. Remove @nullable and replace with /*?*/ migration hint
4. Run dart migrate (I don't know if this will complain about missing part files, but if this is the case you can run it with --ignore-errors probably, or not delete the part files and run a find and replace to remove the annotation in the generated files)
5. Generate the files

**Comment by rrousselGit** [comment] 2021-03-06 19:14
You definitely shouldn't upgrade Freezed _before_ `dart migrate`

Freezed will generate null-safe code anyway, so that'd prevent `dart migrate` from working because of compilation errors.
I'd just ignore the warnings about Freezed not being null-safe

The warning is more of a false positive, because of how code-generation works.

**Comment by TimWhiting** [comment] 2021-03-06 19:37
I would recommend adding that to the readme under instructions for migrating to nullsafety.

**Comment by rrousselGit** [comment] 2021-03-09 11:32
Closing since this is expected

**Closed by rrousselGit** 2021-03-09 11:32 UTC
Labels: bug, needs triage

**Comment by esDotDev** [comment] 2021-03-16 05:14
Just hit this myself, we're migrating a large code base, doing the bulk of it by hand since it's just quicker than using the tool, and the tool has bugs like the inability to toggle directories. 

Didn't realize that `freezed` should go last, and lost about an hr because @nullable went away and we started getting compiler errors on null assignment. Searching the readme for @nullable yielded no results, which was a bit confusing. A quick mention of the change would've helped.

Thanks for the clarification @TimWhiting, discarding local changes now and will do `freezed` last!

**Comment by davidmartos96** [comment] 2021-03-16 07:58
@esDotDev Have you tried the migration tool that comes with Flutter 2.0? It comes with directory toggles, which weren't available when the tool first came out in Beta Dart. You should give it another try 😉

**Comment by esDotDev** [comment] 2021-03-16 15:29
Yep, I logged a bug against it 
https://github.com/dart-lang/sdk/issues/45326#issuecomment-800264116
