### ISSUE TITLE
Serialization other than JSON

### ISSUE THREAD

**Issue by lukepighetti** [rrousselGit/freezed#794] opened 2022-11-05 17:33 UTC
Would be nice to implement a generic serialization interface so that we can add serialization methods that are not JSON

**Comment by rrousselGit** [comment] 2022-11-05 20:51
I do not understand what this is about. Could you clarify?

**Comment by lukepighetti** [comment] 2022-11-05 22:30
Here's a list of possible data formats one might want to use for sending data classes over the wire. Freezed uses JSON, but if we wanted to implement others, I don't believe there is a way to achieve that today. https://serde.rs/#data-formats

**Comment by rrousselGit** [comment] 2022-11-06 10:43
fromJson/toJSon would likely support them all, unless I'm missing something?

Freezed doesn't parse the String. It simply transforms a Map into a class. Support for other formats should be the responsibility of dart:convert or whatever else you use for parsing your String.

There's possibly a naming issue; "fromJson" not necessarily being the most appropriate name.
But Freezed uses that because dart:convert hard-coded support for calling `toJson` methods.

**Comment by lukepighetti** [comment] 2022-11-06 13:23
This feature request is to support serialization methods other than JSON, without using JSON as the intermediary format.

**Comment by rrousselGit** [comment] 2022-11-07 10:56
Honestly I'm lost.   Freezed doesn't _really_ deal with JSON. It only receives a Map.

Could you write a concrete example?

**Comment by SunlightBro** [comment] 2022-11-07 12:02
As much as I love the concept of just adding some annotation
```dart
@Dataclass
@Serialize
class MyClass {
  final int foo;
  final String? bar;
}
```

And I get a constructor that handles serialisation for me like:
```dart
MyClass.fromPostcard(Uint8List bytes) // or some other format 
```

I think this has to wait till dart has proper [Metaprogramming](https://github.com/dart-lang/language/issues/1482), similar to macros in rust.

At the moment freezed only passes the responsibility over to json_serializable, which alone already results in a lot of issues/regression-tests every time the transitive_dependencies fall out of sync (build_runner, analyzer, ...)

**Comment by lukepighetti** [comment] 2022-11-08 12:37
> Honestly I'm lost. Freezed doesn't _really_ deal with JSON. It only receives a Map.
> 
> Could you write a concrete example?

Right now freezed passes all serialization responsibility to `json_serializable`.

I'm asking it to deal with serialization directly, and in a way that is format/protocol agnostic. `serde` for Rust is a good example.

**Comment by rrousselGit** [comment] 2022-11-08 13:56
But that's the thing. I'm arguing that json_serializable is technically format/protocol agnostic.   
The naming is unfortunate, but you could use it with non-JSON formats if you wanted. Right?

In the end, Freezed and json_serializable convert a Map into a class. Neither of them directly deal with JSON

I've used Freezed/json_serializable to decode Yaml before with no issue.  
So I insist in saying that I don't understand what the issue is, concretely.


It'd help if you could write a sample of what you want.

**Comment by rrousselGit** [comment] 2022-11-29 11:15
To be clear, what I mean is, `from/toJson` aren't actually dealing with JSON. They already are generic. It's more of a naming issue than a flexibility issue

In the end, you still have to use `jsonDecode` explicitly:

```dart
final map = jsonDecode('{"foo": 42}');

MyClass.fromJson(map);
```


Replacing `jsonDecode` with anything else "just works".
like:

```dart
final map = yamlDecode('''
foo: 42
''');

MyClass.fromJson(map);
```

**Comment by II11II** [comment] 2022-12-20 08:00
@rrousselGit I suppose @lukepighetti is confused by names ```fromJson``` and ```toJson``` methods
Perhaps, he wants renaming ```fromJson``` and ```toJson``` to   ```fromMap``` and ```toMap``` correspondingly

**Comment by rrousselGit** [comment] 2022-12-20 09:08
Right I mentioned that.

But fromJson/toJson is what's used by nearly everything. Lots of things rely of them being named fromJson/toJson, even if it's not really "JSON"

**Comment by II11II** [comment] 2022-12-20 09:20
Can freezed serialize and deserialize to map from other methods of class?
f.e.

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';
part 'model.g.dart';

@freezed
class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromMap(Map<String, dynamic> map) => _$ModelFromMap(map);
}
```

**Comment by dmrickey** [comment] 2023-02-15 20:18
> Right I mentioned that.
> 
> But fromJson/toJson is what's used by nearly everything. Lots of things rely of them being named fromJson/toJson, even if it's not really "JSON"

So if I legitimately want "JSON" then what's the correct way to do it? Is there a "thisIsReallyTo/FromJson" methods? Like, I understand that the current `toJson` method returns a map and not a string, but I'd like a `toJson` method that actually does what its name says it does. So is there a way to either read from or convert an object to a json string?

**Comment by rrousselGit** [comment] 2023-02-15 20:23
jsonEncode(obj.toJson())

**Comment by LaysDragon** [comment] 2023-03-29 13:56
I bump into some situation but not sure if it is related here. 
The model using under firebase firestore also used in functions call. so there have too level of serialization standard. For functions,its need pure Map,so toJson can handle. But for firestore,its a half Map data,its have some type (ex.timestamp) that don't need convert into json compatibility type. So its likely almost 98% same with `toJson` but slight different. It would be nice if I can create some variants with code generator like `toDocument` `fromDocument`,and not to confused or conflicted with `toJson` `fromJson`.

**Comment by rrousselGit** [comment] 2023-05-24 14:03
Closing as this is more a naming issue than an actual "freezed only supports JSON format".

**Closed by rrousselGit** 2023-05-24 14:03 UTC
Labels: enhancement, question

**Comment by lukepighetti** [comment] 2023-05-26 18:03
Perhaps a concrete case will be more informative.

Consider the use case of wanting to use Freezed data classes, but instead of JSON as your transport format, you want to use MessagePack.

It would be nice if Freezed (like serde) had the tools necessarily to generate serialization methods for an arbitrary transport format.

https://pub.dev/packages/messagepack

**Comment by rrousselGit** [comment] 2023-05-26 18:45
@lukepighetti you can convert the bytes into a map, and send that to Freezed
