### ISSUE TITLE
0.12.3 build_runner blocks and never finishes with union classes that use several params of the same (freeze) type

### ISSUE THREAD

**Issue by suchafreak** [rrousselGit/freezed#320] opened 2020-12-12 16:58 UTC
The following simple Freezded `Trouble` class results in `build_runner` running forever; activity monitor in macOs shows a `dart` process at 100% CPU usage.

```Dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'sp_test.freezed.dart';

@freezed
abstract class A with _$A {
  const factory A.first() = First;
  const factory A.second() = Second;
}

@freezed
abstract class Trouble with _$Trouble {
  const factory Trouble.trouble2(A a1, A a2) = _Trouble2;
  const factory Trouble.trouble3(A a1, A a2, A a3) = Trouble3;
  const factory Trouble.trouble4(A a1, A a2, A a3, A a4) = _Trouble4;
}
```
Removing any of the `.trouble`-factory declarations results in a successful build_runner run.
Using String instead of A also makes the problem go away.

This is the easiest test case that I was able to come up with in order to show the problem I encountered in a slightly more involved scenario.

Thanks for looking into this.
Cheers
-sascha

**Comment by rrousselGit** [comment] 2020-12-12 17:26
Closing as duplicate of https://github.com/rrousselGit/freezed/issues/312

**Closed by rrousselGit** 2020-12-12 17:26 UTC
Labels: bug, needs triage
