### ISSUE TITLE
Unable to run build_runner - The getter 'imports' isn't defined for the class 'PrefixElement'

### ISSUE THREAD

**Issue by Kilian-Perisset** [rrousselGit/freezed#700] opened 2022-07-06 20:56 UTC
Hey,

**Describe the bug**
After having installed latest freezed dependencies (following the docs), when I launch `build_runner` (with or without freezed classes in the project), it displays this : 
```
% flutter packages pub run build_runner build --delete-conflicting-outputs  

[INFO] Generating build script...
[INFO] Generating build script completed, took 664ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph because the language version of some package(s) changed. This would most commonly happen when updating dependencies or changing your min sdk constraint.
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 13ms

[INFO] Generating build script...
[INFO] Generating build script completed, took 136ms

[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script......
[WARNING] /opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/freezed-2.0.4/lib/src/tools/type.dart:27:16: Error: The getter 'imports' isn't defined for the class 'PrefixElement'.
 - 'PrefixElement' is from 'package:analyzer/dart/element/element.dart' ('/opt/homebrew/Caskroom/flutter/2.10.4/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/dart/element/element.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'imports'.
      return e.imports.any((l) {
               ^^^^^^^
[INFO] Precompiling build script... completed, took 1.3s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78
```

**To Reproduce**

1. Install all the dependencies following [freezed documentation](https://github.com/rrousselGit/freezed#install), so : 
```
json_annotation: ^4.5.0
freezed_annotation: ^2.0.3
  
(in dev deps)
freezed: ^2.0.4
json_serializable: ^6.2.0
build_runner: ^2.1.11
  ``` 
2. Then, run `flutter packages pub run build_runner build --delete-conflicting-outputs`
3. You'll maybe get this error

I tried to upgrade and downgrade some dependencies and to repair Flutter pub cache. it doesn't work

**Expected behavior**
I would expect to have my `.g.` files generated and my freezed classes too

**Environment** 
- Flutter (Channel stable, 2.10.4, on macOS 12.4 21F79 darwin-arm)
- Other used dependencies (`retrofit`, `dio`, `retrofit_generator`, `http`, `get`) 

Thank you for your help !

**Comment by Hacker437** [comment] 2022-07-07 04:24
@Kilian-Perisset The problem is with the analyzer package, freezed requires version 4.2.0 make sure you add in your dev dependencies

**Comment by Kilian-Perisset** [comment] 2022-07-07 09:58
Ok thank you ! 👍

**Comment by dzsonni** [comment] 2022-07-07 12:43
Until the PR is merged you can use an override:
`dependency_overrides:
  analyzer: ">=4.2.0 <5.0.0"`

**Comment by mariopepe** [comment] 2022-07-08 18:04
Freezed version 2.0.4 should have been marked as containing breaking changes.

I am using Flutter 2.10.5 and I have in my dev dependencies `freezed: ^2.0.3+1` with the carrot operator `^`.

Of course this is now broken as Analyzer 4.2.0 as per the [changelog](https://pub.dev/packages/analyzer/changelog) "Updates SDK constraints to >=2.17.0 <3.0.0.".

Now I had to remove the carrot operator and go for `freezed: 2.0.3+1`. Which does not seem ideal, and I am guessing many dev out there in my same situation had to go over some inconvenience to figure it out.

**Comment by FireAndIceFrog** [comment] 2022-07-11 01:28
Has this been resolved? I am experiencing the same error

**Comment by antOnioOnio** [comment] 2022-07-11 11:57
Having the same problem.  Any advance?

**Comment by mariopepe** [comment] 2022-07-11 12:03
@antOnioOnio for the time being change your dependencies to `freezed: 2.0.3+1`.

Important, remove the carrot operator `^`

For the package maintainer, this is not the first time a wide spread issue makes it into production in freezed. While thanking you for the great package and the great work, may I humbly propose to prioritise the creation of more tests? Best

**Comment by antOnioOnio** [comment] 2022-07-11 13:07
@mariopepe  thanks.

**Comment by rrousselGit** [comment] 2022-07-11 13:12
I'll bump Freezed later today.

**Closed** 2022-07-12 07:18 UTC
Labels: bug, needs triage

**Comment by yogithesymbian** [comment] 2022-08-10 15:16
> freezed: 2.0.3+1



> @antOnioOnio for the time being change your dependencies to `freezed: 2.0.3+1`.
> 
> Important, remove the carrot operator `^`
> 
> For the package maintainer, this is not the first time a wide spread issue makes it into production in freezed. While thanking you for the great package and the great work, may I humbly propose to prioritise the creation of more tests? Best

i still got the error but i solve by fixing dependency does not match but its a lot of list need to fix so i force to update my sdk / flutter to stable version `flutter upgrade --force` in `stable channel`. now its work .
