### ISSUE TITLE
`import as` causes problems with code generation

### ISSUE THREAD

**Issue by HosseinYousefi** [rrousselGit/freezed#475] opened 2021-07-14 11:17 UTC
**Describe the bug**
Using dataclasses that have types imported using the syntax `import '...' as something;` doesn't work.

**To Reproduce**
a.dart:
```dart
import 'b.dart' as b;
import 'package:freezed_annotation/freezed_annotation.dart';

part 'a.freezed.dart';

@freezed
class A with _$A {
  const factory A(b.B value) = _A;
}
```

b.dart:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'b.freezed.dart';

@freezed
class B with _$B {
  const factory B(int value) = _B;
}
```

**Expected behavior**
We expect the generator to work.
However, the generated `a.freezed.dart` doesn't include the necessary `b.` prefix and causes errors.

**Comment by SunlightBro** [comment] 2021-07-14 12:08
Duplicate of #70

**Comment by rrousselGit** [comment] 2021-07-14 15:02
Closing as duplicate of #70

**Closed by rrousselGit** 2021-07-14 15:02 UTC
Labels: bug, needs triage
