### ISSUE TITLE
generated xxx.g.dart error

### ISSUE THREAD

**Issue by gaohongliang** [rrousselGit/freezed#1027] opened 2023-12-26 05:13 UTC
```
@Freezed(genericArgumentFactories:true)
class Response<T> with _$Response<T> {
  const factory Response({
    @JsonKey(name: 'RequestId') required String requestId,
    @JsonKey(name: 'Error') required Error? error,
    @JsonKey(name: 'Data') dynamic data,
  }) = _Response<T>;

  factory Response.fromJson(Map<String, Object?> json, T Function(dynamic) fromJsonT) =>
      _$ResponseFromJson<T>(json,fromJsonT);
}

@Freezed(genericArgumentFactories: true)
class ServerResponse<T> with _$ServerResponse<T> {
  const factory ServerResponse({
    @JsonKey(name: 'Response') required Response<T> response,
  }) = _ServerResponse<T>;

  factory ServerResponse.fromJson(
          Map<String, Object?> json, T Function(dynamic) fromJsonT) =>
      _$ServerResponseFromJson<T>(json, fromJsonT);
}
```

execute this command
`dart run build_runner build`

class Response generated succes,but ServerResponse failed.
```
[INFO] Generating build script completed, took 451ms
[INFO] Reading cached asset graph completed, took 294ms
[INFO] Checking for updates since last build completed, took 1.4s
[SEVERE] json_serializable on lib/models/server_response.dart:

RangeError (index): Invalid value: Only valid value is 0: -1
[INFO] Running build completed, took 2.6s
[INFO] Caching finalized dependency graph completed, took 192ms
```

**Comment by rrousselGit** [comment] 2023-12-26 14:13
Duplicate of https://github.com/rrousselGit/freezed/issues/887

**Closed by rrousselGit** 2023-12-26 14:13 UTC
Labels: bug, needs triage

**Comment by dwkim891220** [comment] 2024-01-23 04:56
i hope this comment help you
https://github.com/rrousselGit/freezed/issues/766#issuecomment-1817080034
