### ISSUE TITLE
"Unhandled Exception: 'null': Switch case fall-through at line null." when using multiple constructors

### ISSUE THREAD

**Issue by NotoriousV2** [rrousselGit/freezed#78] opened 2020-02-28 18:22 UTC
Hello,

When using multiple constructors and attempting to use the `Model.fromJson` method, I get the error `Unhandled Exception: 'null': Switch case fall-through at line null.`.

If I comment out one of the constructors and attempt again, all is fine. Am I doing something wrong here? Thanks.

This does not work:
```
@freezed
abstract class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```

This works:
```
@freezed
abstract class Model with _$Model {
  factory Model.first(String a) = First;
  // factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```

```
void main() {
  final jsonString = '{"a": "foo"}';
  print(Model.fromJson(jsonDecode(jsonString)));
}
```

**Comment by rrousselGit** [comment] 2020-02-28 18:25
Freezed requires an extra `runtimeType` property in the json when deserializing unions.

You didn't pass it, therefore freezed throws

**Comment by knaeckeKami** [comment] 2020-02-29 21:06
In case you don't control the json, you can use a custom JsonConverter.

Example:

```dart
class MyDataConverter implements JsonConverter<MyData, Map<String, dynamic>> {
  const MyDataConverter();

  @override
  MyData fromJson(Map<String, dynamic> json) {
    if(json == null){
      return null;
    }
    //type data was already set (e.g. because we serialized it ourselves)
    if (json["runtimeType"] != null) {
      return MyData.fromJson(json);
    }
    if( isTypeA){ // you need to find some condition to know which type it is. e.g. check the presence of some field in the json
         return MyDataA.fromJson(json);
    }
    else if(isTypeB){
        return MyDataB.fromJson(json);
    }
 }

  @override
  Map<String, dynamic> toJson(MyData data) => data.toJson();
}
```

**Comment by rrousselGit** [comment] 2020-03-01 18:55
Closing this since it is the expected behavior

**Closed by rrousselGit** 2020-03-01 18:55 UTC
Labels: question

**Comment by scopendo** [comment] 2020-06-12 16:22
@rrousselGit – this makes sense. It might be helpful to update the documentation on pub.dev to state this, along with the `JsonConverter` suggestion mentioned by @knaeckeKami.

The documentation at the moment doesn't quite make that clear.

> for classes with multiple constructors, Freezed will take care of deciding which constructor should be used.

**Comment by rrousselGit** [comment] 2020-06-12 16:32
Indeed.
Do you want to make a pull request? 😊

**Comment by scopendo** [comment] 2020-06-13 13:01
👍  #198 

@knaeckeKami – I've included almost verbatim the example converter that you suggested above.
