### ISSUE TITLE
How to serialize enum-like unions (without values)?

### ISSUE THREAD

**Issue by proninyaroslav** [rrousselGit/freezed#251] opened 2020-08-19 17:52 UTC
Hi. Suppose I have a class like this:
```Dart
@freezed
abstract class Enum with _$Enum {
  const factory Enum.one() = EnumOne;
  const factory Enum.two() = EnumTwo;
  const factory Enum.three() = EnumThree;
}
```
To each of them I want to assign a constant string value (`'one'`, `'two'`, `'three'`) to be able to serialize/deserialize `EnumOne`, `EnumTwo` and `EnumThree` objects. Is it possible to implement this somehow (Freezed-like style)?

**Comment by rrousselGit** [comment] 2020-08-20 07:46
Freezed does not support de/serialization from/to String. It only supports Maps

**Comment by rrousselGit** [comment] 2020-08-20 07:47
Duplicate of #74

**Closed by rrousselGit** 2020-08-20 07:47 UTC

**Comment by proninyaroslav** [comment] 2020-08-20 14:57
@rrousselGit 
Maybe it's possible to specify a private field in each union member  to store their string representation?

**Comment by proninyaroslav** [comment] 2020-08-20 15:17
The only solution I could think of:
```Dart
@freezed
abstract class Enum with _$Enum {
  const Enum._();

  const factory Enum.one() = EnumOne;
  const factory Enum.two() = EnumTwo;
  const factory Enum.three() = EnumThree;

  static const Map<String, Enum> _jsonMap = {
    'one': Enum.one(),
    'two': Enum.two(),
    'three': Enum.three(),
  };

  static Enum fromJson(String value) => _jsonMap[value];

  String toJson() => when(
        one: () => 'one',
        two: () => 'two',
        three: () => 'three',
      );
}
```

**Comment by rrousselGit** [comment] 2020-08-20 15:26
Freezed already use the constructor name, but it isn't serialized into a string. It's serialized into a Map that contains a string.

**Comment by rrousselGit** [comment] 2020-08-20 15:44
No the json won't be empty. Using the OP class, if you did toJson then fromJson, this correctly instantiate the correct class

The json contains more than just the properties. It contains the Metadata of which constructor was used

**Comment by proninyaroslav** [comment] 2020-08-20 16:28
@rrousselGit 
I checked the behavior. It turned out that Freezed doesn't add `runtimeType` key to the output json, if a union contains only one member (e.g only `factory Enum.one()`). As a result, an empty json map - `{}`. This doesn't suitable for me, because I'm storing this information in the DB, and the union currently only contains one member, but more members will be added to the union in the future.
