### ISSUE TITLE
@late getters are not being considered by coverage tools

### ISSUE THREAD

**Issue by paulononaka** [rrousselGit/freezed#290] opened 2020-10-21 13:57 UTC
**Describe the bug**
I have some custom late getters that even though the code is being unit tested Freezed tricks the coverage tools because in the generated code the getters are overridden with the source copied and never calls super, so my original code is actually never called.

**To Reproduce**

```Dart
@freezed
abstract class ComplexLate implements _$ComplexLate {
  ComplexLate._();
  factory ComplexLate(List<int> values) = _ComplexLate;

  @late
  List<int> get odd => values.where((value) {
        if (value.isOdd)
          return true;
        else
          return false;
      }).toList();
}
```

```Dart
test('complex late', () {
    final complex = ComplexLate([0, 1, 2, 3, 4]);

    expect(complex.odd, [1, 3]);

    expect(identical(complex.odd, complex.odd), isTrue);
  });
```

ps: I'm using Flutter and I am not sure how to use lcov to generate the report for Dart, but I believe it is something similar.
ps 2: Install lcov with brew or apt-get.
```sh
flutter test --coverage
genhtml -q -o coverage coverage/lcov.info
open coverage/index.html
```

**Expected behavior**
The method `odd` should show as covered in the report.

**Comment by rrousselGit** [comment] 2020-10-21 14:21
That is caused by the "late" decorator

I don't think I will fix it before nnbd is released. And by the time we have NNBD, `@late` will be deprecated

I'd suggest just ignoring it or not using the late decorator if you don't need it

**Comment by paulononaka** [comment] 2020-10-21 16:40
@rrousselGit agree with you, but I'm not sure how long it would take to get into Flutter.

It seems easy to change the generated code to call super, but it works only for classes that `implements`, it doesn't work for `with` and since I'm quite new to Flutter/Dart I don't really understand it yet. By now I'm just ignoring as you said, but I'm willing to study it more and open a PR if you think it would help Flutter's people since now. Or if you already know how to solve it for `with` too I'd open a PR faster with your guidance. It is up for you. Thanks for the lib, it is great.

Btw, I've updated the issue to mention @late.

**Comment by ali-alizadeh** [comment] 2021-02-02 18:39
Another thing which I think is related to this issue is that coverage tools also do not consider that private constructor which should be defined when defining methods or getters in freezed classes.

Considering the following example:
```dart
@freezed
abstract class ProfileSummary implements _$ProfileSummary {
  const factory ProfileSummary({
    @required Id id,
    @required String userId,
    @required String firstName,
    @required String lastName,
    @required Option<String> aliasName,
  }) = _ProfileSummary;

  const ProfileSummary._();

  String get name => aliasName.fold(() => '$firstName $lastName', (a) => a);
}
```
The coverage tool generates this:
![image](https://user-images.githubusercontent.com/46545247/106646499-d1219380-655b-11eb-95fb-75350f90c562.png)

I there anyway to fix this?

**Comment by rrousselGit** [comment] 2021-03-20 22:27
Closing as starting from 0.14.0, there is no-longer a `@late` decorator

**Closed by rrousselGit** 2021-03-20 22:27 UTC
Labels: bug
