### ISSUE TITLE
Conflict with the current flutter SDK at installing

### ISSUE THREAD

**Issue by SalahAdDin** [rrousselGit/freezed#485] opened 2021-07-26 07:40 UTC
**Describe the bug**
Every time i try to update this package i get a conflict between it and the flutter SDK:
```shell
❯ flutter pub get
Because freezed_annotation >=0.14.3 depends on json_annotation ^4.1.0 which depends on meta ^1.4.0, freezed_annotation >=0.14.3 requires meta ^1.4.0.
And because every version of flutter from sdk depends on meta 1.3.0, freezed_annotation >=0.14.3 is incompatible with flutter from sdk.
So, because thesis_cancer depends on both flutter any from sdk and freezed_annotation ^0.14.3, version solving failed.
Running "flutter pub get" in thesis_cancer...                           
pub get failed (1; So, because thesis_cancer depends on both flutter any from sdk and freezed_annotation ^0.14.3, version solving failed.)
```

**To Reproduce**

Just try to update it with the current SDK.

**Expected behavior**
It should not give any error and update.

```shell
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by rrousselGit** [comment] 2021-07-26 08:23
It seems that you are on an older version of Flutter. Try upgrading your Flutter SDK, which uses a more up-to-date version of `meta`

**Comment by SalahAdDin** [comment] 2021-07-26 08:55
> It seems that you are on an older version of Flutter. Try upgrading your Flutter SDK, which uses a more up-to-date version of `meta`

I think i did it:
 ```shell
Flutter is already up to date on channel stable
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (4 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by SunlightBro** [comment] 2021-07-26 09:47
@SalahAdDin 
The current version of `flutter stable` is still stuck using `meta: 1.3.0`,
If you simply use `freezed 0.14.2` you should be fine on stable for now.

With the next flutter stable release (`2.4.x`) you will need to upgrade.

**Comment by rrousselGit** [comment] 2021-08-06 15:12
The problem isn't Freezed but json_annotation which uses 1.4.0

Maybe consider using a dependency override:

```yaml
dependency_overrides:
  meta: ^1.3.0
```

or switch flutter channel

Freezed uses ^1.3.0, so there's nothing that can be done on my hand.
I could downgrade json_annotation to 4.0.0, but this would drop support on json_serializable 5.0.0

So I'm going to close this.

**Closed by rrousselGit** 2021-08-06 15:12 UTC
Labels: question

**Comment by SalahAdDin** [comment] 2021-08-06 17:30
> The problem isn't Freezed but json_annotation which uses meta 1.4.0
> 
> Maybe consider using a dependency override:
> 
> ```yaml
> dependency_overrides:
>   meta: ^1.3.0
> ```
> 
> or switch flutter channel
> 
> Freezed uses ^1.3.0, so there's nothing that can be done on my side of things.
> I could downgrade json_annotation to 4.0.0, but this would drop support on json_serializable 5.0.0
> 
> So I'm going to close this.

Thanks, let's wait to the new **flutter** release.

**Comment by jonasbark** [comment] 2021-08-19 12:51
Thanks @SunlightBro

**Comment by lloydrichards** [comment] 2021-09-01 19:24
Have the same issue when using Freezed with Flutter_Intl. Have tried the dependency_overrides as suggested but get this error:
```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-2.1.0/lib/src/error/best_practices_verifier.dart:326:50: Error: The getter 'displayString' isn't defined for the class 'TargetKind'.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'displayString'.
        var kindNames = kinds.map((kind) => kind.displayString).toList()
                                                 ^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-2.1.0/lib/src/error/best_practices_verifier.dart:328:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
        var validKinds = kindNames.commaSeparatedWithOr;
                                   ^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-2.1.0/lib/src/error/best_practices_verifier.dart:1722:40: Error: Getter not found: 'topLevelVariable'.
      return kinds.contains(TargetKind.topLevelVariable);
                                       ^^^^^^^^^^^^^^^^
```
pub finished with exit code 1
``When running flutter pub run build_runner build``

Any suggestions?
