### ISSUE TITLE
Concrete member not applied

### ISSUE THREAD

**Issue by wim07101993** [rrousselGit/freezed#355] opened 2021-01-29 12:28 UTC
**Describe the bug**
The `toString` method of a class is not correcty applied.

**To Reproduce**

#### `credentials.dart`
```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'credentials.freezed.dart';

@freezed
abstract class Credentials with _$Credentials {
  Credentials._();

  factory Credentials({
    String username,
    String password,
  }) = _Credentials;

  @override
  String toString() => 'Credentials(username: $username, password: ********)';
}
```
#### test
```dart
test('should contain fields with obfuscated password', () {
  // act
  final str = credentials.toString();

  // assert
  expect(str, contains('Credentials'));
  expect(str, contains('username: ${credentials.username}'));
  expect(str, contains('password: ********'));
});
```
#### test result:
```
Expected: contains 'password: ********'
  Actual: '_$_Credentials#e8b9e(type: Credentials, username: silas-yost@west.ca, password: dWc7mDOD5gz4e)oP9S)'
```

**Expected behavior**
The `toString` method should work as described.

**Extra info**
I have tried manipulating this class in many ways to to get it working with the builder but for this class it does not seem to work. Which is strange because in another file I use exactly the same methods and there it works...

**Comment by rrousselGit** [comment] 2021-03-01 16:33
Duplicate of #170

**Comment by rrousselGit** [comment] 2021-03-01 16:35
Duplicate of https://github.com/rrousselGit/freezed/issues/221

**Closed by rrousselGit** 2021-03-01 16:35 UTC
Labels: bug, needs triage

**Comment by rockerhieu** [comment] 2021-07-09 03:54
@rrousselGit either that or we can add an annotation to censor the value in `toString()`. What do you think about this?

```dart
class Censored {
  const Censored(value);

  final String value;
}
```

```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'credentials.freezed.dart';

@freezed
abstract class Credentials with _$Credentials {
  Credentials._();

  factory Credentials({
    String username,
    @Censored('********')
    String password,
  }) = _Credentials;
}
```

`toString()` should output something like this:

```
_$_Credentials#e8b9e(type: Credentials, username: silas-yost@west.ca, password: ********)oP9S)'
```
