### ISSUE TITLE
Parameters can't override default values Warning

### ISSUE THREAD

**Issue by marcos930807** [rrousselGit/freezed#73] opened 2020-02-26 20:39 UTC
Hi, this is more like a Question, i have this union class:
@freezed
abstract class Union<T> with _$Union<T> {
  const factory Union.initial() = Initial<T>;
  const factory Union.loaded(T value) = Data<T>;
  const factory Union.loading() = Loading<T>;
  const factory Union.error([Failure failure, String message]) =
      ErrorDetails<T>;
}
After generating the file, ToString method rise a Warning:
Parameters can't override default values, this method overrides 'DiagnosticableTreeMixin.toString' where 'minLevel' has a different value.
Try using the same default value in both methods.

I wonder if I missed something, how can I get rid of this warning.
Thanks for your awesome works

**Comment by rrousselGit** [comment] 2020-02-27 13:54
Closing as duplicate of #48

**Closed by rrousselGit** 2020-02-27 13:54 UTC
