### ISSUE TITLE
generator error Formatter exception (Adds an asterix(*) after type(String)

### ISSUE THREAD

**Issue by shriharip** [rrousselGit/freezed#387] opened 2021-03-12 10:16 UTC
**Describe the bug**
[SEVERE] freezed:freezed on lib/env.dart:
An error `FormatterException` occurred while formatting the generated source for
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

**To Reproduce**

1. create a  new flutter project and install the freezed dependencies
2. create a dart file env.dart
````
import 'package:freezed_annotation/freezed_annotation.dart';
part 'env.freezed.dart';
@freezed

class Env with _$Env {
  factory Env(String envtype) = _Env;
}
````

**Expected behavior**
should create a error free part file but it generates the part file with exceptions

```
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides

part of 'env.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;


final _privateConstructorUsedError = UnsupportedError('It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more informations: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

/// @nodoc
class _$EnvTearOff {
  const _$EnvTearOff();

_Env call( String* envt) {
  return  _Env(envt,);
}

}

/// @nodoc
const $Env = _$EnvTearOff();

/// @nodoc
mixin _$Env {

 String* get envt => throw _privateConstructorUsedError;






@JsonKey(ignore: true)
$EnvCopyWith<Env> get copyWith => throw _privateConstructorUsedError;

}

/// @nodoc
abstract class $EnvCopyWith<$Res>  {
  factory $EnvCopyWith(Env value, $Res Function(Env) then) = _$EnvCopyWithImpl<$Res>;
$Res call({
 String* envt
});



}

/// @nodoc
class _$EnvCopyWithImpl<$Res> implements $EnvCopyWith<$Res> {
  _$EnvCopyWithImpl(this._value, this._then);

  final Env _value;
  // ignore: unused_field
  final $Res Function(Env) _then;

@override $Res call({Object? envt = freezed,}) {
  return _then(_value.copyWith(
envt: envt == freezed ? _value.envt : envt // ignore: cast_nullable_to_non_nullable
as String*,
  ));
}

}


/// @nodoc
abstract class _$EnvCopyWith<$Res> implements $EnvCopyWith<$Res> {
  factory _$EnvCopyWith(_Env value, $Res Function(_Env) then) = __$EnvCopyWithImpl<$Res>;
@override $Res call({
 String* envt
});



}

/// @nodoc
class __$EnvCopyWithImpl<$Res> extends _$EnvCopyWithImpl<$Res> implements _$EnvCopyWith<$Res> {
  __$EnvCopyWithImpl(_Env _value, $Res Function(_Env) _then)
      : super(_value, (v) => _then(v as _Env));

@override
_Env get _value => super._value as _Env;

@override $Res call({Object? envt = freezed,}) {
  return _then(_Env(
envt == freezed ? _value.envt : envt // ignore: cast_nullable_to_non_nullable
as String*,
  ));
}


}



/// @nodoc
class _$_Env  implements _Env {
   _$_Env(this.envt);

  

@override  final String* envt;

@override
String toString() {
  return 'Env(envt: $envt)';
}


@override
bool operator ==(dynamic other) {
  return identical(this, other) || (other is _Env&&(identical(other.envt, envt) || const DeepCollectionEquality().equals(other.envt, envt)));
}

@override
int get hashCode => runtimeType.hashCode ^ const DeepCollectionEquality().hash(envt);

@JsonKey(ignore: true)
@override
_$EnvCopyWith<_Env> get copyWith => __$EnvCopyWithImpl<_Env>(this, _$identity);






}


abstract class _Env implements Env {
   factory _Env( String* envt) = _$_Env;
  

  

@override  String* get envt => throw _privateConstructorUsedError;
@override @JsonKey(ignore: true)
_$EnvCopyWith<_Env> get copyWith => throw _privateConstructorUsedError;

}
```

**Comment by iamim** [comment] 2021-03-14 14:10
I had the same issue after upgrading to the latest version. Updating SDK constraint to `>=2.12.0 <3.0.0` (enables null-safety) resolved the issue.

**Comment by rrousselGit** [comment] 2021-03-14 15:04
This indeed appears to be caused by an outdated dart SDK, so I'll close this.

**Closed by rrousselGit** 2021-03-14 15:04 UTC
Labels: bug, needs triage
