### ISSUE TITLE
Freezed removes import prefixes on code generation

### ISSUE THREAD

**Issue by MatthewCoetzee412** [rrousselGit/freezed#272] opened 2020-09-25 23:52 UTC
###
**The bug**
---
When I use "flutter packages pub run build_runner watch" and generate the Freezed files it removes the import prefixes I have. 
Just to clarify what I mean by import prefixes, below is an example:

```Dart
import '.../food.dart' as food;
import '.../some_other_package_with_the_same_name_as_food.dart;
```
###
**To Reproduce**
---
Initially have or create two classes with the same name but different functionality and import them inside the same file to use with Freezed. You would have to use import prefixes as demostrated above to do this. Then run "flutter packages pub run build_runner watch"

###
**Expected behavior**
---
It should keep the import prefixes but it doesn't meaning I have to edit the generated freezed file by hand and add the prefixes to the class I used it for.

**Comment by rrousselGit** [comment] 2020-09-26 12:56
Duplicate of #70

**Closed by rrousselGit** 2020-09-26 12:56 UTC
Labels: bug, needs triage
