### ISSUE TITLE
Static JSON serialisation functions aren't called properly in the generated code

### ISSUE THREAD

**Issue by hacker1024** [rrousselGit/freezed#408] opened 2021-03-22 09:21 UTC
**Describe the bug**
Consider the following JSON:

```json
{
  "fruits": "apple,orange,pear"
}
```

A simple class to represent this data would look like this:

```dart
@freezed
class FruitData with _$FruitData {
  factory FruitData({
    @JsonKey(
      name: 'fruits',
      fromJson: _readCommaSeparatedList,
      toJson: _writeCommaSeparatedList,
    )
        required List<String> fruits,
  }) = _FruitData;
}

factory FruitData.fromJson(Map<String, dynamic> json) => _$FruitDataFromJson(json);

static List<String> _readCommaSeparatedList(String list) => list.split(',');

static String _writeCommaSeparatedList(List<String> list) => list.join(',');
```

The code generated from this, however fails to compile. This is because the static methods used are used in the generated code without the class being prefixed; `_readCommaSeparatedList` is used instead of `FruitData._readCommaSeparatedList`. The following factory declaration, for example, works around the issue:

```dart
  factory FruitData({
    @JsonKey(
      name: 'fruits',
      fromJson: FruitData._readCommaSeparatedList,
      toJson: FruitData._writeCommaSeparatedList,
    )
        required List<String> fruits,
  }) = _FruitData;
```

**To Reproduce**
Use the code above.

**Expected behavior**
When static functions are used in this way, they should be prefixed with the class name in the generated code.

**Comment by rrousselGit** [comment] 2021-03-22 11:16
Duplicate of #123

I would advise against using static functions and place the functions outside the class instead

**Closed by rrousselGit** 2021-03-22 11:16 UTC
Labels: bug, needs triage
