### ISSUE TITLE
Doesn't work with named imports

### ISSUE THREAD

**Issue by lukepighetti** [rrousselGit/freezed#147] opened 2020-04-15 18:43 UTC
I've noticed that if you create a freezed class and one of the fields uses a named import, ie

```dart
import "package:mypackage/mypackage.dart" as myPackage;

part 'foo.freezed.dart';

/// Contains app global authentication data
@freezed
abstract class Foo with _$Foo {
  factory Foo({
    @required myPackage.Bar bar,
  }) = _ Foo;
}
```

The generated code will try to use `Bar` instead of `myPackage.Bar`

**Comment by rrousselGit** [comment] 2020-04-15 18:50
Closing as duplicate of #70

**Comment by rrousselGit** [comment] 2020-04-15 18:50
As far as I'm aware, there's no easy way to do that

**Closed by rrousselGit** 2020-04-15 18:50 UTC

**Comment by lukepighetti** [comment] 2020-04-15 19:31
@rrousselGit what's the limitation?
