### ISSUE TITLE
generator error for default argument of not generated factory

### ISSUE THREAD

**Issue by dan-leech** [rrousselGit/freezed#384] opened 2021-03-09 11:14 UTC
**Describe the bug**
I get error for default argument value of not generated factory: `The parameter `defaultValue` of `Test` is non-nullable but is neither required nor marked with @Default` from `freezed_annotation: ^0.14.0`, `freezed: ^0.14.0+1`

**To Reproduce**
```Dart
@freezed
class Test with _$Test {
  const Test._();

  factory Test._constructor({
    @Default(0) num val,
  }) = _Test;

  factory Test({num defaultValue = 0}) => Test._constructor(val: defaultValue);
}
```

**Expected behavior**
no error for class methods and factories that are not present in generated freezed file.

**Comment by shovelmn12** [comment] 2021-03-09 13:26
this just happened to me even if i added a `?`
I was using some class i generated using freezed as an optional in another class
after playing around with it I think the problem is that the generator can't find the class I am using and therefor using `dynamic` instead.

example:
```
@freezed
class Ref with _$Ref {
      const factory Ref.user(properties...) = UserRef;
      
      const factory Ref.dog(properties...) = DogRef;
}
```

```
@freezed
class Toy with _$Toy {
      const factory Toy.puppet({
                    UserRef? madeBy,
              }) = PuppetToy;
      
      const factory Toy.whatever({
                    UserRef? madeBy,
              }) = WhateverToy;
}
```

when running the generator I always get an error saying: ``The parameter `madeBy` of `Toy.puppet` is non-nullable but is neither required nor marked with @Default``
and when I do add `required` it just uses type `dynamic` instead of `UserRef?`

hopefully you can resolve this issue ASAP :)

**Comment by dan-leech** [comment] 2021-03-09 15:26
@shovelmn12 Your issue is different.
Your factories are involved in code generation, mine factory not.

I think yours issue is a bug too.

**Comment by BrianMwas** [comment] 2021-03-09 15:49
I have had the issue for two days now its really been a back breaker

**Comment by shovelmn12** [comment] 2021-03-09 16:54
@dan-leech yeah maybe.. ill open another issue :)

**Comment by rrousselGit** [comment] 2021-03-14 13:33
Duplicate of #358

**Closed by rrousselGit** 2021-03-14 13:33 UTC
Labels: bug, needs triage
