### ISSUE TITLE
The annotation 'JsonKey' can only be used on fields or getters (invalid_annotation_target)

### ISSUE THREAD

**Issue by HugoHeneault** [rrousselGit/freezed#527] opened 2021-10-05 10:16 UTC
**Describe the bug**
When using `@JsonKey` annotation and the required keyword, I got this notice: 

```
info: The annotation 'JsonKey' can only be used on fields or getters (invalid_annotation_target at [test_app] lib/models/user.dart:11)
```

**To Reproduce**
Using AndroidStudio 2020.3.1, create this class:
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User(
      {required String name,
      required String email,
      @JsonKey(name: 'created_at') required DateTime createdAt}) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
```
Run the builder, look at the dart analysis panel, you'll get the notice.

**Expected behavior**
Well... the notice shouldn't be here?

Thanks alot for this *awesome* package! :-)

**Comment by HugoHeneault** [comment] 2021-10-05 10:22
Here's my `flutter doctor -v` output: 


```
flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale fr-FR)
    • Flutter version 2.5.2 at /Users/hugo/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hugo/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/hugo/Library/Android/sdk/
    • Java binary at: /Users/hugo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/hugo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/hugo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/hugo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • FC475F02-494C-45EA-B072-D6CDAA3ACAFC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```

**Comment by rrousselGit** [comment] 2021-10-05 10:31
Closing as duplicate of https://github.com/rrousselGit/freezed/issues/488

This is a known issue. I'd recommend disabling the warning like shown in the readme.

**Closed by rrousselGit** 2021-10-05 10:31 UTC
Labels: bug, needs triage

**Comment by HugoHeneault** [comment] 2021-10-05 10:38
Oh my bad. Didn't catch it! Thanks for the workarounds on the know issue and your - as always - fast and precise answer. :-)
