### ISSUE TITLE
Support JsonSerializable(createToJson: false)

### ISSUE THREAD

**Issue by AlexandrFarkas** [rrousselGit/freezed#318] opened 2020-12-09 09:22 UTC
**Describe the bug**
Option "createToJson: false" generates code with error, because freezed tries to call the code, which has not been generated.
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'api_flight.g.dart';
part 'api_flight.freezed.dart';


@freezed
abstract class ApiFlight with _$ApiFlight {
  @JsonSerializable(createToJson: false)
  factory ApiFlight(
    String cityFrom,
    String cityFromCode,
    String cityTo,
    String cityToCode
  ) = _ApiFlight;

  factory ApiFlight.fromJson(Map<String, dynamic> json) => _$ApiFlightFromJson(json);
}

```

**To Reproduce**
Generated code in _$_ApiFlight:
```
@override
  Map<String, dynamic> toJson() {
    return _$_$_ApiFlightToJson(this); // HERE IS ERROR, _$_$_ApiFlightToJson doesn't exist.
  }
```
**Expected behavior**
toJson shouldn't be generated, if createToJson is false

**Comment by maks** [comment] 2020-12-23 07:06
This is will happen even if you remove `createToJson: false` because that has not yet been implemented in Freezed, so this is essentially a duplicate of #190 .

**Comment by JErazo7** [comment] 2021-06-14 17:15
Is there any update about this topic?

**Comment by rrousselGit** [comment] 2021-10-14 16:59
But I'll close this in favor of #190

**Closed by rrousselGit** 2021-10-14 16:59 UTC
Labels: enhancement

**Comment by trqhien** [comment] 2021-12-21 12:00
One use case is when using custom Json converter. Sometimes, it's not straight forward to convert some data types to JSON. For example 

```dart
@freezed
abstract class Transaction implements _$Transaction {
  const Transaction._();

  @JsonSerializable(createToJson: false)
  const factory Transaction({
    @required String date,
    @required String amount,
    @JsonKey(fromJson: Transaction._typeConverted) @required TransactionType type,
    @JsonKey(fromJson: Transaction._statusConverted) @required TransactionStatus status,
  }) = _Transaction;

  factory Transaction.fromJson(Map<String, dynamic> json) => _$TransactionFromJson(json);

  static TransactionStatus _statusConverted(String status) {
    if (status == "success") {
      return TransactionStatus.success;
    } else if (status == "failed") {
      return TransactionStatus.fail;
    } else if (status == "processing") {
      return TransactionStatus.processing;
    } else {
      throw Exception("Unsupported `TransactionStatus` of $status");
    }
  }

  static TransactionType _typeConverted(String type) {
    if (type.toLowerCase() == "buy") {
      return = TransactionType.buy();
    } else if ((type.toLowerCase() == "sell")) {
      return TransactionType.sell();
    } else {
      throw Exception("Unsupported `TransactionType` of $type");
    }
  }
}

@freezed
abstract class TransactionType with _$InvestmentTransactionType {
  const factory TransactionType.buy() = Buy;
  const factory TransactionType.sell() = Sell;
}

enum TransactionStatus {
  success,
  fail,
  processing
}

```

Sometimes we only need decode JSON to our desired models, not the other way around. And having to write custom `toJson` method for each custom converter seem unnecessary and overkilled. That's why in [json_serializable](https://pub.dev/packages/json_serializable) , they allow you to do this

```dart
@JsonSerializable(createToJson: false)
class SomeClass {
  ...
}
```

The only workaround I can think of is to create a general `toJson` converter that throw an exception and use it with `@JsonKey` decorator like this

```dart
@freezed
abstract class Transaction implements _$Transaction {
  const Transaction._();

  const factory Transaction({
    @required String date,
    @required String amount,
    @JsonKey(
      fromJson: Transaction._typeConverted,
      toJson: Transaction._invalidToJson
    )
    @required TransactionType type,
    @JsonKey(
      fromJson: Transaction._statusConverted,
      toJson: Transaction._invalidToJson
    ) 
    @required TransactionStatus status,
  }) = _Transaction;

  factory Transaction.fromJson(Map<String, dynamic> json) => _$TransactionFromJson(json);

  static TransactionStatus _statusConverted(String status) {
   ...
  }

  static TransactionType _typeConverted(String type) {
   ...
  }

  static dynamic _invalidToJson(dynamic data) => throw Exception("");
}
```
