### ISSUE TITLE
@Default doesn't work with static methods

### ISSUE THREAD

**Issue by RaviKavaiya** [rrousselGit/freezed#166] opened 2020-05-10 04:33 UTC
Assume following class:

```dart
@freezed
abstract class TestClass implements _$TestClass {
  const TestClass._();

  const factory TestClass({
    @Default('MyName') String testString,
    // MyChildTest child,
  }) = _TestClass;

  static TestClass getInstance({String x}) {
    return TestClass(testString: x);
  }
}
```

The class throws an assertion error when I return its instance from the static method.

The following _WORKS_:
```dart
TestClass m = TestClass.getInstance(x: 'Something');
```

While, the following throws **assertion error:** _'testString != null': is not true._
```dart
TestClass m = TestClass.getInstance();
```

**Expected behavior:**
- As we have specified `@Default`, it should take `'MyName'` automatically.

My intention to use `static` method is, to not allow the user instantiate the class with all properties. Some properties would be generated (e.g., Some random string, etc.)

**Comment by rrousselGit** [comment] 2020-05-10 04:47
The issue is not Freezed but Dart here.

You should instead write:

```dart
  static TestClass getInstance({String x = 'MyName' }) {
    return TestClass(testString: x);
  }
```

**Comment by RaviKavaiya** [comment] 2020-05-10 05:03
Hi @rrousselGit thanks. I also tried to have a look and found this:
https://github.com/dart-lang/sdk/issues/33918

And, I came to know that this is not Freezed issue. 

In above link, there are some suggestions.


Currently, we are doing like this in generated class:

```dart
const _$_TestClass({this.testString = 'default_value'})
      : assert(myname != null),
        super._();
```

My proposal is, can we do something like this?

```dart
const _$_TestClass({String tempTestString = 'default_value'})
      : this.testString  = tempTestString ?? 'default_value'
        super._();
```

As you can see, the `assert` is removed. 
**If `@nullable` is provided, **, the default behavior (the current one) seems OK.

Your thoughts?

**Comment by rrousselGit** [comment] 2020-05-10 05:15
I don't think that's a good idea, because that would prevent people from assigning `null` to the property

**Comment by RaviKavaiya** [comment] 2020-05-10 05:18
But, we can use @nullable for that.
If any field contains, @nullable, default behavior to be used.
If not @nullable, then only use newly proposed syntax.

**Comment by rrousselGit** [comment] 2020-05-10 05:23
But that won't work once we have non-nullable types

**Comment by AntiqPeace** [comment] 2020-05-10 05:53
@rrousselGit I like @RaviKavaiya 's idea. This would be very much helpful to developers by eliminating most boilerplate code.

By the way, I don't understand :

> But that won't work once we have non-nullable types

Can you please elaborate, how @RaviKavaiya 's approach would not work in NNBD?

**Comment by rrousselGit** [comment] 2020-05-10 06:13
```dart
  static TestClass getInstance({String x }) {
    return TestClass(testString: x);
  }
```

This code won't compile anymore.

To fix the error, you will have to revert back to writing:

```dart
  static TestClass getInstance({String x = 'MyName' }) {
    return TestClass(testString: x);
  }
```

So that would be only a temporary solution.

**Comment by rrousselGit** [comment] 2020-05-29 20:24
I don't plan on doing anything related to this, so I'll close it for now

**Closed by rrousselGit** 2020-05-29 20:24 UTC
