### ISSUE TITLE
[question] About copyWith

### ISSUE THREAD

**Issue by pedromassango** [rrousselGit/freezed#225] opened 2020-07-05 17:22 UTC
Why we need to call `copyWith.call` and not just copyWith?

Why this:
`state.copyWith.call(isLoading: true)`
Instead of:
`state.copyWith(isLoading: true)`

**Comment by rrousselGit** [comment] 2020-07-05 17:48
You can write `state.copyWith(isLoading: true)`

`.call` is something all functions have.

```dart
void example() {
}

void main() {
  example.call();
}
```

**Comment by pedromassango** [comment] 2020-07-05 20:00
I'm trying this is and it is not working

**Comment by rrousselGit** [comment] 2020-07-05 20:15
That's not a helpful description of the problem. It is working, as shown by the test suite

**Comment by pedromassango** [comment] 2020-07-05 22:24
Yes. sorry I was waching Brancelona. Here is the version info:

```yaml
freezed: ^0.11.2
freezed_annotation: ^0.11.0
````

The real issue is that without `.call()` the code completion is not working you need to type the complete property name and if it is valid the compiler will not show the error.

In this case I need to type `loadProjectsFailure` without code completion help
`state.copyWith(loadProjectsFailure: result)`

And this have code completion:
`state.copyWith.call(loadProjectsFailure: result)`

**Comment by rrousselGit** [comment] 2020-07-05 22:35
That's a duplicate of https://github.com/rrousselGit/freezed/issues/137 then.

There's nothing I can do, it's a bug in the analyzer, not in Freezed. 
The autocomplete should work.

**Closed by rrousselGit** 2020-07-05 22:35 UTC
