### ISSUE TITLE
`The name 'T' isn't a type so it can't be used as a type argument.`  generating  State of flutter_bloc

### ISSUE THREAD

**Issue by Kulwinder-Singh-Rahal** [rrousselGit/freezed#154] opened 2020-04-23 05:25 UTC
I have created generic Result<T> class using freeze and using it inside state of flutter_bloc for one property, here is my _Result_ implementation

```
import 'package:freezed_annotation/freezed_annotation.dart';
part 'result.freezed.dart';

@freezed
abstract class Result<T> with _$Result<T> {
  const factory Result.loading() = Loading<T>;
  const factory Result.data(T t) = Data<T>;
  const factory Result.error([Error e, String message]) = Error<T>;
}
```

Here is _HomeState_

```
part of 'home_bloc.dart';

@freezed
abstract class HomeState with _$HomeState {
  const factory HomeState.main({
    @required Result<List<String>> manufacturer,
  }) = Main;
}
```

but when `$HomeStateCopyWith<$Res>` and other similar classes generated than its <T> is not replaced with `List<String>` and i'm getting `The name 'T' isn't a type so it can't be used as a type argument.`  
this is generated class where is problem

```
abstract class $HomeStateCopyWith<$Res> {
  factory $HomeStateCopyWith(HomeState value, $Res Function(HomeState) then) =
      _$HomeStateCopyWithImpl<$Res>;
  $Res call({Result<List<String>> manufacturer});

  $ResultCopyWith<T, $Res> get manufacturer;
}

class _$HomeStateCopyWithImpl<$Res> implements $HomeStateCopyWith<$Res> {
  _$HomeStateCopyWithImpl(this._value, this._then);

  final HomeState _value;
  // ignore: unused_field
  final $Res Function(HomeState) _then;

  @override
  $Res call({
    Object manufacturer = freezed,
  }) {
    return _then(_value.copyWith(
      manufacturer: manufacturer == freezed
          ? _value.manufacturer
          : manufacturer as Result<List<String>>,
    ));
  }

  @override
  $ResultCopyWith<T, $Res> get manufacturer {
    if (_value.manufacturer == null) {
      return null;
    }
    return $ResultCopyWith<T, $Res>(_value.manufacturer, (value) {
      return _then(_value.copyWith(manufacturer: value));
    });
  }
}

abstract class $MainCopyWith<$Res> implements $HomeStateCopyWith<$Res> {
  factory $MainCopyWith(Main value, $Res Function(Main) then) =
      _$MainCopyWithImpl<$Res>;
  @override
  $Res call({Result<List<String>> manufacturer});

  @override
  $ResultCopyWith<T, $Res> get manufacturer;
}

class _$MainCopyWithImpl<$Res> extends _$HomeStateCopyWithImpl<$Res>
    implements $MainCopyWith<$Res> {
  _$MainCopyWithImpl(Main _value, $Res Function(Main) _then)
      : super(_value, (v) => _then(v as Main));

  @override
  Main get _value => super._value as Main;

  @override
  $Res call({
    Object manufacturer = freezed,
  }) {
    return _then(Main(
      manufacturer: manufacturer == freezed
          ? _value.manufacturer
          : manufacturer as Result<List<String>>,
    ));
  }
}
```
 here i guess <T> could be replaced with `List<String>`

**Comment by Kulwinder-Singh-Rahal** [comment] 2020-04-24 15:46
**is there any workaround that i can use for now ?**
because this is blocking me from creating state as i wanted

**Comment by chimon2000** [comment] 2020-04-27 06:29
This is a duplicate of #128.  At the moment the only workaround is to manually edit the generated class.

**Comment by rrousselGit** [comment] 2020-05-06 21:53
Closing this as a duplicate

**Closed by rrousselGit** 2020-05-06 21:53 UTC

**Comment by mohammadne** [comment] 2020-09-29 10:41
https://github.com/rrousselGit/freezed/issues/128#issuecomment-700619362
