### ISSUE TITLE
`unqualified_reference_to_non_local_static_member` on `static const` member

### ISSUE THREAD

**Issue by kzrnm** [rrousselGit/freezed#967] opened 2023-08-18 12:01 UTC
**Describe the bug**

Generator create uncompilable file. [unqualified_reference_to_non_local_static_member](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=unqualified_reference_to_non_local_static_member#unqualified_reference_to_non_local_static_member) occurred on `static const` member.

**To Reproduce**

Use `static const` as `@Default` argument.

*todo.dart*

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'todo.freezed.dart';

@freezed
class Todo with _$Todo {
  const Todo._();

  const factory Todo({
    @Default(defaultValue) int num,
  }) = _Todo;

  static const defaultValue = 20;
}
```

*todo.freezed.dart*

```dart
class _$_Todo extends _Todo {
  const _$_Todo({this.num = defaultValue}) : super._();
```

**Expected behavior**

*todo.freezed.dart*

```dart
class _$_Todo extends _Todo {
  const _$_Todo({this.num = Todo.defaultValue}) : super._();
```

**Comment by rrousselGit** [comment] 2023-08-18 12:34
Duplicate of https://github.com/rrousselGit/freezed/issues/123

**Closed by rrousselGit** 2023-08-18 12:34 UTC
Labels: bug, needs triage
