### ISSUE TITLE
Union toJson include unionkey/value

### ISSUE THREAD

**Issue by nonoyona** [rrousselGit/freezed#839] opened 2023-01-12 17:14 UTC
If I currently convert a union to json the unionKey and value are not added to the Json (as far as I understood, pls correct me if I am wrong on this).
I was thinking that it would be cool if there was an option to add that value to the json, so that fromJson and toJson stay consistent if it's needed.
If there is already a way to achieve that, could someone maybe tell me how, cause I haven't found anything to that on the internet.

**Comment by artebiakin** [comment] 2023-03-27 10:38
@nonoyona 
yes, we don't have any extra fields, but you can easily override your `toJson()` method like so:

```dart
  @override
  Map<String, dynamic> toJson() {
    return super.toJson()
      ..addAll({
        'runtimeType': runtimeType,
      });
  }
```

**Comment by rrousselGit** [comment] 2023-03-27 18:02
I'm not sure what this issue is about.

You mean that unions don't contain the unique type value necessary for fromJson in their toJson?

**Comment by artebiakin** [comment] 2023-04-05 10:00
@rrousselGit 
Now I remember one way how to reproduce it. 
The problem is this: when you use a named constructor, the `runtimeType` will not be added. But it will be added if there are two or more (named) constructors. Adding a private constructor won't solve the problem.

Here is an example of models. Pay attention to tests. 1 out of 3 will pass.
https://github.com/artebiakin/freezed_demo

and thank u for your work!

**Comment by rrousselGit** [comment] 2023-04-05 10:24
Right, that's expected.

If there's only a single constructor defining properties, you didn't define a union.
A union is when there are at least two different kinds of `factory Class.name(...) = Name;`

If there's only one, that's a normal class. The key isn't needed for decoding the object.

**Comment by rrousselGit** [comment] 2023-04-19 09:12
In the lack of a reply, I'll close this.

So far the current behavior is expected. If you think there's something undesired here, please open a new issue with more information.

**Closed by rrousselGit** 2023-04-19 09:12 UTC
Labels: question
