### ISSUE TITLE
Error message about toString() implementation

### ISSUE THREAD

**Issue by sdebruyn** [rrousselGit/freezed#67] opened 2020-02-24 13:17 UTC
The minimum level in the mixin is _debug_, but it's _info_ in the generated code.  Dart complains about this because you can't change the default value when you override a method.

![image](https://user-images.githubusercontent.com/963413/75155319-19abbc80-5710-11ea-84d3-f7c0e5de2c6e.png)

![image](https://user-images.githubusercontent.com/963413/75155356-2c25f600-5710-11ea-9922-264e321532a6.png)

**Comment by rrousselGit** [comment] 2020-02-24 13:21
Duplicate of #48 
You are using a channel that is not up to date with the latest Flutter changes.

This default value changed and `freezed` is using the updated one.

**Closed** 2020-02-24 13:35 UTC
