### ISSUE TITLE
Override toJson does not work

### ISSUE THREAD

**Issue by ChivialK** [rrousselGit/freezed#87] opened 2020-03-04 05:47 UTC
```dart
@freezed
abstract class GameEntity with _$GameEntity {
  const factory GameEntity({
    @required int id,
    @required String cname,
    @required String gameUrl,
  }) = _GameEntity;

  @override
  factory GameEntity.fromJson(Map<String, dynamic> json) {
    return GameEntity(
      gameUrl: '${json['platform']}/${json['gameid']}',
      cname: json['cname'],
      id: json['id'],
    );
  }

  ///This fails
  @override
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    final info = gameUrl.split('/');
    data['cname'] = cname;
    data['gameid'] = info[1];
    data['id'] = id;
    data['platform'] = info[0];
    return data;
  }
}
/// This works well
extension GameEntityExtension on GameEntity {
  Map<String, dynamic> extJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    final info = gameUrl.split('/');
    data['cname'] = cname;
    data['gameid'] = info[1];
    data['id'] = id;
    data['platform'] = info[0];
    return data;
  }
}
```

Test Class
```dart
test('test entity to json', () {
    String gameJson = '{"id": 4107, "platform": "eg", "gameid": "candy", "cname": "糖果世界"}';

    GameEntity gameEntity = GameEntity(id: 4107, gameUrl: "eg/candy", cname: "糖果世界",);

    Map<String, dynamic> test(GameEntity entity) {
      final Map<String, dynamic> data = new Map<String, dynamic>();
      final info = entity.gameUrl.split('/');
      print('split url: $info');
      data['category'] = info[0];
      data['cname'] = entity.cname;
      data['gameid'] = info[2];
      data['id'] = entity.id;
      data['platform'] = info[1];
      return data;
    }

    print('------------method in test------------');
    final mapJson = json.decode(gameJson);
    print('decoded from json string: $mapJson');
    final mapEntity1 = test(gameEntity);
    print('test mapped: $mapEntity1');
    print('------------method in class------------');
    final mapEntity2 = gameEntity.extJson();
    print('ext mapped: $mapEntity2');
    final mapEntity3 = gameEntity.toJson();
    print('override mapped: $mapEntity3');
    expect(mapEntity3, equals(mapJson));
  });
```

Test Results
```dart
------------method in test------------
decoded from json string: {id: 4107, platform: eg, gameid: candy, cname: 糖果世界}
split url: [eg, candy]
test mapped: {cname: 糖果世界, gameid: candy, id: 4107, platform: eg}
------------method in class------------
/// expected json map
ext mapped: {cname: 糖果世界, gameid: candy, id: 4107, platform: eg}
/// override not working
override mapped: {id: 4107, cname: 糖果世界, gameUrl: eg/candy}
```

The @override method does not show hint, so the toJson() call still returns the generated _$_$_GameEntityToJson(this)?

**Comment by rrousselGit** [comment] 2020-03-04 23:28
Methods are not supported yet. I'll close this as duplicate of #83, which is the issues to support methods & co

**Closed by rrousselGit** 2020-03-04 23:28 UTC

**Comment by avalanche-tm** [comment] 2022-08-15 20:23
Was this resolved? Overriding toJson function still doesn't have effect.

**Comment by RakaAlrian** [comment] 2023-02-23 05:33
still not working, any work around?

**Comment by ahmedhnewa** [comment] 2023-05-31 20:31
Still not working

**Comment by lucasepple** [comment] 2023-06-23 06:23
Also came across this issue

```dart
@freezed
class TestClass with _$TestClass {
  const TestClass._();

  const factory TestClass({
    @JsonKey(
      name: 'created_at',
      toJson: _dateTimeToJson,
      fromJson: _dateTimeFromJson,
    )
    required DateTime createdAt,
    required String other,
  }) = _TestClass;

  static int _dateTimeToJson(DateTime value) =>
      value.millisecondsSinceEpoch;
  static DateTime _dateTimeFromJson(int value) =>
      DateTime.fromMillisecondsSinceEpoch(value);

  factory TestClass.fromJson(Map<String, dynamic> json) =>
      _$TestClassFromJson(json);
}
```
and got this error message
```
: Error: Undefined name '_dateTimeToJson'.
      name: 'created_at', toJson: _dateTimeToJson, fromJson: _dateTimeFromJson)
: Error: Undefined name '_dateTimeFromJson'.
      name: 'created_at', toJson: _dateTimeToJson, fromJson: _dateTimeFromJson)
```

**Comment by lucasepple** [comment] 2023-06-23 06:46
Managed to solve my issue with this post: https://stackoverflow.com/questions/67150713/freezed-and-json-serializable-how-to-use-a-custom-converter
